# Generated by Django 4.2.25 on 2026-04-14 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_browser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='browsersession',
            name='platform',
            field=models.CharField(choices=[('x', 'X (Twitter)'), ('instagram', 'Instagram'), ('gbp', 'Google Business Profile'), ('tiktok', 'TikTok')], max_length=20, verbose_name='プラットフォーム'),
        ),
    ]
