#!/bin/bash
# deploy_mac.sh
# Stable deployment script for CircuitPython Pico 2 W on macOS
# Addresses FAT12 filesystem incompatibility and macOS metadata pollution

set -euo pipefail

# Color codes
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${GREEN}=== CircuitPython macOS Deployment ===${NC}"

# Suppress AppleDouble file creation
export COPYFILE_DISABLE=1

# 1. Mount Detection
MOUNT_POINT="/Volumes/CIRCUITPY"

if [ ! -d "$MOUNT_POINT" ]; then
    echo -e "${RED}ERROR: CIRCUITPY not mounted at $MOUNT_POINT${NC}"
    echo "Please connect your Pico 2 W device via USB"
    echo ""
    echo "Available volumes:"
    ls -1 /Volumes/
    exit 1
fi

echo -e "${BLUE}Target: $MOUNT_POINT${NC}"

# Display device info (non-blocking)
if command -v diskutil &> /dev/null; then
    echo -e "${BLUE}Device info:${NC}"
    diskutil info "$MOUNT_POINT" 2>/dev/null | grep -E '(Device Node|Volume Name|File System|Total Size)' || echo "(diskutil info unavailable)"
    echo ""
fi

# 2. Create settings.toml to disable AutoReload
echo -e "${BLUE}Step 1: Configuring AutoReload prevention...${NC}"
cat > "${MOUNT_POINT}/settings.toml" << 'EOF'
# Auto-generated by deploy_mac.sh
# Prevents device reboot during file transfers
CIRCUITPY_AUTORELOAD = 0
EOF

if [ -f "${MOUNT_POINT}/settings.toml" ]; then
    echo -e "${GREEN}✓ settings.toml created${NC}"
else
    echo -e "${YELLOW}⚠ Warning: Could not create settings.toml${NC}"
fi

# 3. Pre-deployment cleanup: Fix file/directory conflicts
echo -e "${BLUE}Step 2: Pre-deployment conflict check...${NC}"

fix_dir_conflict() {
    local target="${MOUNT_POINT}/$1"
    if [ -f "$target" ]; then
        echo -e "${YELLOW}⚠ CONFLICT: $1 is a file, should be directory. Fixing...${NC}"
        rm -f "$target" || {
            echo -e "${RED}✗ Failed to remove conflicting file: $1${NC}"
            exit 1
        }
    fi
    mkdir -p "$target" || {
        echo -e "${RED}✗ Failed to create directory: $1${NC}"
        exit 1
    }
}

# Ensure critical directories exist
fix_dir_conflict "lib"
fix_dir_conflict "lib/adafruit_character_lcd"
fix_dir_conflict "lib/adafruit_mcp230xx"
fix_dir_conflict "lib/adafruit_minimqtt"
fix_dir_conflict "sensors"
fix_dir_conflict "actuators"

echo -e "${GREEN}✓ Conflict check complete${NC}"

# 4. Main deployment using safe rsync
echo -e "${BLUE}Step 3: Syncing files to device...${NC}"
echo "Source: $(pwd)"
echo ""

# Determine source directory
if [ -f "code.py" ] && [ -d "lib" ]; then
    SOURCE_DIR="."
elif [ -f "MB_IoT_device_main/code.py" ]; then
    SOURCE_DIR="MB_IoT_device_main"
else
    echo -e "${RED}ERROR: Cannot find source directory with code.py${NC}"
    echo "Run this script from the project root or MB_IoT_device_main directory"
    exit 1
fi

# Safe rsync with FAT12-compatible options
if rsync -av \
    --inplace \
    --omit-dir-times \
    --no-perms \
    --no-owner \
    --no-group \
    --exclude='.Trashes/' \
    --exclude='.fseventsd/' \
    --exclude='.Spotlight-V100/' \
    --exclude='.vscode/' \
    --exclude='._*' \
    --exclude='.DS_Store' \
    --exclude='__pycache__/' \
    --exclude='*.pyc' \
    --exclude='.git/' \
    --exclude='.gitignore' \
    --exclude='scripts/' \
    --exclude='docs/' \
    --exclude='*.md' \
    --exclude='*.sh' \
    --exclude='*.bak' \
    --exclude='*.disabled' \
    --exclude='*.disabled.py' \
    --exclude='*.example.py' \
    --exclude='*.sample' \
    --exclude='.vscode/' \
    --exclude='MB_IoT.code-workspace' \
    --exclude='*.uf2' \
    "${SOURCE_DIR}/" "${MOUNT_POINT}/"; then
    echo -e "${GREEN}✓ File sync complete${NC}"
else
    echo -e "${RED}✗ rsync failed${NC}"
    echo ""
    echo -e "${YELLOW}Common causes:${NC}"
    echo "  - USB connection interrupted (check cable)"
    echo "  - Device rebooted mid-transfer (AutoReload issue)"
    echo "  - Filesystem corruption (try formatting device)"
    exit 1
fi

# 5. Post-deployment cleanup
echo -e "${BLUE}Step 4: Cleaning macOS metadata files...${NC}"

# Use dot_clean to merge AppleDouble files
if command -v dot_clean &> /dev/null; then
    dot_clean -m "$MOUNT_POINT" 2>/dev/null || echo -e "${YELLOW}⚠ dot_clean had warnings (non-fatal)${NC}"
    echo -e "${GREEN}✓ AppleDouble files merged${NC}"
fi

# Remove remaining ._* files (except in system directories)
find "$MOUNT_POINT" -name '._*' -type f 2>/dev/null | while read -r file; do
    # Skip files in .Trashes and .fseventsd
    if [[ ! "$file" =~ \.Trashes ]] && [[ ! "$file" =~ \.fseventsd ]]; then
        rm -f "$file" 2>/dev/null || true
    fi
done

# Remove .DS_Store files
find "$MOUNT_POINT" -name '.DS_Store' -type f -delete 2>/dev/null || true

echo -e "${GREEN}✓ Metadata cleanup complete${NC}"

# 6. Mandatory sync to commit all writes
echo -e "${BLUE}Step 5: Flushing filesystem buffers...${NC}"
sync
echo -e "${GREEN}✓ Filesystem sync complete${NC}"

# 7. Health Check
echo ""
echo -e "${BLUE}Step 6: Health check...${NC}"

HEALTH_OK=true

# Check: adafruit_character_lcd must be a directory
if [ ! -d "${MOUNT_POINT}/lib/adafruit_character_lcd" ]; then
    echo -e "${RED}✗ BROKEN: lib/adafruit_character_lcd is not a directory!${NC}"
    if [ -f "${MOUNT_POINT}/lib/adafruit_character_lcd" ]; then
        echo "  (It's a file - metadata corruption detected)"
    else
        echo "  (It's missing entirely)"
    fi
    HEALTH_OK=false
else
    echo -e "${GREEN}✓ lib/adafruit_character_lcd is a directory${NC}"
fi

# Check: code.py exists
if [ ! -f "${MOUNT_POINT}/code.py" ]; then
    echo -e "${RED}✗ MISSING: code.py not found on device${NC}"
    HEALTH_OK=false
else
    echo -e "${GREEN}✓ code.py exists${NC}"
fi

# Check: settings.toml exists
if [ ! -f "${MOUNT_POINT}/settings.toml" ]; then
    echo -e "${YELLOW}⚠ WARNING: settings.toml missing (AutoReload may interrupt transfers)${NC}"
else
    echo -e "${GREEN}✓ settings.toml exists${NC}"
fi

# Check: No ._* files outside system directories
METADATA_COUNT=$(find "$MOUNT_POINT" -name '._*' -type f 2>/dev/null | grep -v -E '(\.Trashes|\.fseventsd)' | wc -l | tr -d ' ')
if [ "$METADATA_COUNT" -gt 0 ]; then
    echo -e "${YELLOW}⚠ WARNING: Found $METADATA_COUNT AppleDouble files (._*)${NC}"
    echo "  Run: find $MOUNT_POINT -name '._*' | grep -v -E '(\.Trashes|\.fseventsd)'"
else
    echo -e "${GREEN}✓ No metadata pollution detected${NC}"
fi

echo ""

if [ "$HEALTH_OK" = true ]; then
    echo -e "${GREEN}╔════════════════════════════════════╗${NC}"
    echo -e "${GREEN}║  ✓ DEPLOYMENT SUCCESSFUL 🚀       ║${NC}"
    echo -e "${GREEN}╚════════════════════════════════════╝${NC}"
    echo ""
    echo "Next steps:"
    echo "  1. Safely eject the device (diskutil unmount $MOUNT_POINT)"
    echo "  2. Device will reboot automatically"
    echo "  3. To re-enable AutoReload, delete settings.toml from device"
    exit 0
else
    echo -e "${RED}╔════════════════════════════════════╗${NC}"
    echo -e "${RED}║  ✗ DEPLOYMENT FAILED               ║${NC}"
    echo -e "${RED}╚════════════════════════════════════╝${NC}"
    echo ""
    echo -e "${YELLOW}Troubleshooting:${NC}"
    echo "  - Try formatting the device: ./scripts/format_device_mac.sh"
    echo "  - Check USB connection quality"
    echo "  - Verify source files are intact"
    exit 1
fi
