#!/bin/bash
# format_circuitpy.sh
# FAT12-safe format script for CIRCUITPY volume
# Auto-detects device or accepts manual device node

set -euo pipefail

# Color codes
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

log_info() { echo -e "${BLUE}[INFO]${NC} $*"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $*"; }
log_error() { echo -e "${RED}[ERROR]${NC} $*"; }
log_success() { echo -e "${GREEN}[SUCCESS]${NC} $*"; }

# Parse arguments
SKIP_CONFIRM=false
DEVICE_NODE=""

while [[ $# -gt 0 ]]; do
    case $1 in
        --yes|-y)
            SKIP_CONFIRM=true
            shift
            ;;
        /dev/disk*)
            DEVICE_NODE="$1"
            shift
            ;;
        *)
            log_error "Unknown argument: $1"
            echo "Usage: $0 [--yes] [/dev/diskXsY]"
            exit 1
            ;;
    esac
done

log_info "CIRCUITPY Format Tool (FAT12-safe)"
echo ""

# Auto-detect CIRCUITPY device if not specified
if [ -z "$DEVICE_NODE" ]; then
    log_info "Attempting auto-detection..."
    
    # Try to find CIRCUITPY in diskutil list
    if command -v diskutil &> /dev/null; then
        # Get device node from mounted CIRCUITPY
        if [ -d "/Volumes/CIRCUITPY" ]; then
            DEVICE_NODE=$(diskutil info /Volumes/CIRCUITPY 2>/dev/null | grep "Device Node" | awk '{print $3}')
            if [ -n "$DEVICE_NODE" ]; then
                log_success "Auto-detected CIRCUITPY at: $DEVICE_NODE"
            fi
        fi
        
        # If still not found, search diskutil list
        if [ -z "$DEVICE_NODE" ]; then
            log_warn "CIRCUITPY not currently mounted, searching diskutil list..."
            diskutil list | grep -i "CIRCUITPY" || true
            echo ""
            log_error "Could not auto-detect CIRCUITPY device"
            log_info "Please specify device node manually:"
            log_info "  $0 /dev/diskXsY"
            log_info ""
            log_info "Run 'diskutil list' to find your device"
            exit 1
        fi
    else
        log_error "diskutil command not found (macOS required)"
        exit 1
    fi
fi

# Validate device node format
if [[ ! "$DEVICE_NODE" =~ ^/dev/disk[0-9]+s[0-9]+$ ]] && [[ ! "$DEVICE_NODE" =~ ^/dev/disk[0-9]+$ ]]; then
    log_error "Invalid device node format: $DEVICE_NODE"
    log_info "Expected format: /dev/diskXsY or /dev/diskX"
    exit 1
fi

# Check if device exists
if [ ! -e "$DEVICE_NODE" ]; then
    log_error "Device not found: $DEVICE_NODE"
    exit 1
fi

# Display device information
echo ""
log_info "Target device information:"
diskutil info "$DEVICE_NODE" 2>/dev/null | grep -E '(Device Node|Volume Name|File System|Total Size|Device / Media Name)' || {
    log_error "Cannot get device info for $DEVICE_NODE"
    exit 1
}
echo ""

# Confirmation (unless --yes)
if [ "$SKIP_CONFIRM" = false ]; then
    log_warn "⚠️  WARNING: This will ERASE ALL DATA on $DEVICE_NODE ⚠️"
    echo ""
    read -p "Type 'yes' to confirm format: " CONFIRM
    if [ "$CONFIRM" != "yes" ]; then
        log_info "Format cancelled"
        exit 0
    fi
fi

# Unmount if mounted
log_info "Unmounting device..."
diskutil unmountDisk "$DEVICE_NODE" 2>/dev/null || true

# Format device
log_info "Formatting $DEVICE_NODE as MS-DOS (FAT) with label CIRCUITPY..."
if diskutil eraseDisk MS-DOS CIRCUITPY MBRFormat "$DEVICE_NODE"; then
    log_success "Device formatted successfully"
else
    log_error "Format failed"
    exit 1
fi

# Wait for mount
log_info "Waiting for device to mount..."
sleep 2

# Check if mounted
if [ ! -d "/Volumes/CIRCUITPY" ]; then
    log_warn "CIRCUITPY not auto-mounted, attempting manual mount..."
    diskutil mount "$DEVICE_NODE" || {
        log_error "Failed to mount CIRCUITPY"
        exit 1
    }
    sleep 1
fi

# Verify mount
if [ ! -d "/Volumes/CIRCUITPY" ]; then
    log_error "CIRCUITPY is not mounted at /Volumes/CIRCUITPY"
    exit 1
fi

log_success "CIRCUITPY mounted at /Volumes/CIRCUITPY"

# Create settings.toml to disable AutoReload
log_info "Creating settings.toml (CIRCUITPY_AUTORELOAD=0)..."
cat > "/Volumes/CIRCUITPY/settings.toml" << 'EOF'
# Auto-generated by format_circuitpy.sh
# Prevents device reboot during file transfers
CIRCUITPY_AUTORELOAD = 0
EOF

if [ -f "/Volumes/CIRCUITPY/settings.toml" ]; then
    log_success "settings.toml created"
else
    log_warn "Could not create settings.toml"
fi

# Sync filesystem
log_info "Syncing filesystem..."
sync

# Verify mount status
log_info "Verifying mount..."
if mount | grep -q "CIRCUITPY"; then
    mount | grep "CIRCUITPY"
    log_success "Mount verified"
else
    log_warn "Could not verify mount status"
fi

echo ""
log_success "╔════════════════════════════════════╗"
log_success "║  FORMAT COMPLETE                   ║"
log_success "╚════════════════════════════════════╝"
echo ""
log_info "Next steps:"
log_info "  1. Deploy code: ./scripts/deploy_to_circuitpy.sh"
log_info "  2. Verify: ./scripts/healthcheck_circuitpy.sh"
