# Generated by Django 5.0.4 on 2025-01-15 05:19

import datetime
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={'verbose_name': '予約スケジュール', 'verbose_name_plural': '予約スケジュール'},
        ),
        migrations.RemoveField(
            model_name='customer',
            name='line_user_id',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='customer',
        ),
        migrations.AddField(
            model_name='customer',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='hashed_line_user_id',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='media',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 1, 15, 14, 18, 29, 660268)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='media',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='notice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 1, 15, 14, 18, 34, 531093)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='customer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='hashed_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='memo',
            field=models.TextField(blank=True, default='ここに備考を記入してください。', null=True, verbose_name='備考'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='reservation_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='schedule',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='booking.store'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='position',
            field=models.CharField(default='default_position', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='store',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='店舗情報'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='media',
            name='link',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='media',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='notice',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='notice',
            name='link',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='notice',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='reservation_number',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=255, verbose_name='予約管理番号'),
        ),
    ]
