# Generated by Django 5.0.4 on 2025-01-15 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_schedule_options_remove_customer_line_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='booking.store', verbose_name='店舗'),
        ),
    ]
