# Generated by Django 4.2.25 on 2025-12-04 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0030_remove_schedule_date_schedule_temporary_booked_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IoTDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='デバイス名')),
                ('device_type', models.CharField(choices=[('multi', 'マルチセンサーノード'), ('door', 'スマートロック'), ('other', 'その他')], default='multi', max_length=20, verbose_name='種別')),
                ('external_id', models.CharField(max_length=255, unique=True, verbose_name='デバイスID（AWS側）')),
                ('api_key', models.CharField(max_length=255, verbose_name='APIキー')),
                ('mq9_threshold', models.FloatField(blank=True, null=True, verbose_name='MQ-9閾値')),
                ('alert_enabled', models.BooleanField(default=False, verbose_name='ガス検知アラート有効')),
                ('alert_email', models.EmailField(blank=True, max_length=254, verbose_name='アラート送信メール')),
                ('wifi_ssid', models.CharField(blank=True, max_length=64, verbose_name='Wi-Fi SSID')),
                ('wifi_password', models.CharField(blank=True, max_length=128, verbose_name='Wi-Fi パスワード')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('last_seen_at', models.DateTimeField(blank=True, null=True, verbose_name='最終通信日時')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iot_devices', to='booking.store', verbose_name='店舗')),
            ],
            options={
                'verbose_name': 'IoTデバイス',
                'verbose_name_plural': 'IoTデバイス',
            },
        ),
        migrations.CreateModel(
            name='IoTEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='受信日時')),
                ('event_type', models.CharField(blank=True, max_length=50, verbose_name='イベント種別')),
                ('payload', models.TextField(blank=True, verbose_name='ペイロード(JSON)')),
                ('mq9_value', models.FloatField(blank=True, null=True, verbose_name='MQ-9値')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='booking.iotdevice', verbose_name='デバイス')),
            ],
            options={
                'verbose_name': 'IoTイベントログ',
                'verbose_name_plural': 'IoTイベントログ',
            },
        ),
    ]
