# Generated by Django 4.2.25 on 2025-12-17 11:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0031_iotdevice_iotevent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timer',
            options={'verbose_name': 'タイマー', 'verbose_name_plural': 'タイマー'},
        ),
        migrations.AddField(
            model_name='schedule',
            name='is_cancelled',
            field=models.BooleanField(db_index=True, default=False, verbose_name='キャンセルフラグ'),
        ),
        migrations.AddField(
            model_name='timer',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='iotdevice',
            name='api_key',
            field=models.CharField(db_index=True, max_length=255, verbose_name='APIキー'),
        ),
        migrations.AlterField(
            model_name='iotdevice',
            name='external_id',
            field=models.CharField(db_index=True, max_length=255, unique=True, verbose_name='デバイスID（AWS側）'),
        ),
        migrations.AlterField(
            model_name='iotevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='受信日時'),
        ),
        migrations.AlterField(
            model_name='iotevent',
            name='mq9_value',
            field=models.FloatField(blank=True, db_index=True, null=True, verbose_name='MQ-9値'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='hashed_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='is_temporary',
            field=models.BooleanField(db_index=True, default=True, verbose_name='仮予約フラグ'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='reservation_number',
            field=models.CharField(db_index=True, default=uuid.uuid4, editable=False, max_length=255, verbose_name='予約番号'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start',
            field=models.DateTimeField(db_index=True, verbose_name='開始時間'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='temporary_booked_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='iotevent',
            index=models.Index(fields=['device', 'created_at'], name='booking_iot_device__5dbf2a_idx'),
        ),
        migrations.AddIndex(
            model_name='iotevent',
            index=models.Index(fields=['device', 'mq9_value', 'created_at'], name='booking_iot_device__a9722f_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['staff', 'start'], name='booking_sch_staff_i_2ba6b7_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['staff', 'is_temporary', 'start'], name='booking_sch_staff_i_f3611a_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['staff', 'is_cancelled', 'start'], name='booking_sch_staff_i_dcb69b_idx'),
        ),
    ]
