# Generated by Django 4.2.25 on 2025-12-17 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0032_alter_timer_options_schedule_is_cancelled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='line_user_enc',
            field=models.TextField(blank=True, null=True, verbose_name='LINEユーザーID(暗号化)'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='line_user_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='LINEユーザーIDハッシュ'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['line_user_hash'], name='booking_sch_line_us_f58861_idx'),
        ),
    ]
