# Generated by Django 4.2.27 on 2025-12-18 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0033_schedule_line_user_enc_schedule_line_user_hash_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='カテゴリ名')),
                ('sort_order', models.IntegerField(default=0, verbose_name='並び順')),
            ],
            options={
                'verbose_name': '商品カテゴリ',
                'verbose_name_plural': '商品カテゴリ',
                'ordering': ('store', 'sort_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_line_user_hash', models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='顧客LINEハッシュ')),
                ('table_label', models.CharField(blank=True, default='', max_length=50, verbose_name='席/テーブル')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], db_index=True, default='OPEN', max_length=10, verbose_name='状態')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='booking.schedule', verbose_name='予約')),
            ],
            options={
                'verbose_name': '注文',
                'verbose_name_plural': '注文',
            },
        ),
        migrations.AddField(
            model_name='staff',
            name='is_store_manager',
            field=models.BooleanField(default=False, verbose_name='店長'),
        ),
        migrations.AddField(
            model_name='store',
            name='default_language',
            field=models.CharField(blank=True, default='ja', max_length=10, verbose_name='既定言語'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(db_index=True, max_length=64, verbose_name='SKU')),
                ('name', models.CharField(max_length=200, verbose_name='商品名(デフォルト)')),
                ('description', models.TextField(blank=True, default='', verbose_name='説明(デフォルト)')),
                ('price', models.IntegerField(default=0, verbose_name='価格')),
                ('stock', models.IntegerField(default=0, verbose_name='現在庫')),
                ('low_stock_threshold', models.IntegerField(default=0, verbose_name='閾値')),
                ('last_low_stock_notified_at', models.DateTimeField(blank=True, null=True, verbose_name='閾値通知済み(最後)')),
                ('is_active', models.BooleanField(default=True, verbose_name='公開')),
                ('popularity', models.IntegerField(default=0, verbose_name='人気スコア')),
                ('margin_rate', models.FloatField(default=0.0, verbose_name='利益率(概算)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='booking.category', verbose_name='カテゴリ')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='booking.store', verbose_name='店舗')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
                'ordering': ('store', 'category', 'name'),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=1, verbose_name='数量')),
                ('unit_price', models.IntegerField(default=0, verbose_name='単価')),
                ('status', models.CharField(choices=[('ORDERED', 'Ordered'), ('PREPARING', 'Preparing'), ('SERVED', 'Served'), ('CLOSED', 'Closed')], db_index=True, default='ORDERED', max_length=20, verbose_name='状態')),
                ('note', models.CharField(blank=True, default='', max_length=255, verbose_name='備考')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='booking.order', verbose_name='注文')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='booking.product', verbose_name='商品')),
            ],
            options={
                'verbose_name': '注文明細',
                'verbose_name_plural': '注文明細',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='booking.store', verbose_name='店舗'),
        ),
        migrations.AddField(
            model_name='category',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='booking.store', verbose_name='店舗'),
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('IN', '入庫'), ('OUT', '出庫'), ('ADJUST', '棚卸調整')], db_index=True, max_length=10, verbose_name='種別')),
                ('qty', models.IntegerField(verbose_name='数量')),
                ('note', models.CharField(blank=True, default='', max_length=255, verbose_name='メモ')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('by_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.staff', verbose_name='実施スタッフ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='booking.product', verbose_name='商品')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='booking.store', verbose_name='店舗')),
            ],
            options={
                'verbose_name': '入出庫履歴',
                'verbose_name_plural': '入出庫履歴',
                'indexes': [models.Index(fields=['store', 'created_at'], name='booking_sto_store_i_a4851b_idx'), models.Index(fields=['product', 'created_at'], name='booking_sto_product_89a18f_idx'), models.Index(fields=['movement_type', 'created_at'], name='booking_sto_movemen_7346b8_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(choices=[('ja', '日本語'), ('en', 'English'), ('zh-hant', '繁體中文'), ('zh-hans', '简体中文'), ('ko', '한국어'), ('es', 'Español'), ('pt', 'Português')], db_index=True, max_length=10, verbose_name='言語')),
                ('name', models.CharField(max_length=200, verbose_name='商品名')),
                ('description', models.TextField(blank=True, default='', verbose_name='説明')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='booking.product', verbose_name='商品')),
            ],
            options={
                'verbose_name': '商品翻訳',
                'verbose_name_plural': '商品翻訳',
                'indexes': [models.Index(fields=['lang'], name='booking_pro_lang_4c94db_idx'), models.Index(fields=['product', 'lang'], name='booking_pro_product_254ffc_idx')],
                'unique_together': {('product', 'lang')},
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['store', 'is_active'], name='booking_pro_store_i_9e4df1_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['store', 'category', 'stock'], name='booking_pro_store_i_44be39_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['store', 'sku'], name='booking_pro_store_i_3fade6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('store', 'sku')},
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order', 'status', 'created_at'], name='booking_ord_order_i_dd37f0_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['product', 'created_at'], name='booking_ord_product_af52a4_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['store', 'status', 'created_at'], name='booking_ord_store_i_0acfc9_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer_line_user_hash', 'created_at'], name='booking_ord_custome_fd8a27_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('store', 'name')},
        ),
    ]
