# Generated by Django 5.2.9 on 2025-12-20 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0034_category_order_staff_is_store_manager_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='is_developer',
            field=models.BooleanField(default=False, verbose_name='開発者'),
        ),
    ]
