# Generated by Django 5.2.9 on 2025-12-20 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0035_staff_is_developer'),
    ]

    operations = [
    ]
