# Generated by Django 4.2.25 on 2026-02-21 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0036_add_is_developer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iotdevice',
            name='api_key',
        ),
        migrations.RemoveField(
            model_name='iotdevice',
            name='wifi_password',
        ),
        migrations.AddField(
            model_name='iotdevice',
            name='api_key_hash',
            field=models.CharField(db_index=True, default='', help_text='SHA-256ハッシュ。認証時の照合用', max_length=64, verbose_name='APIキーハッシュ'),
        ),
        migrations.AddField(
            model_name='iotdevice',
            name='api_key_prefix',
            field=models.CharField(blank=True, default='', help_text='管理画面表示用（先頭8文字）', max_length=8, verbose_name='APIキープレフィックス'),
        ),
        migrations.AddField(
            model_name='iotdevice',
            name='wifi_password_enc',
            field=models.CharField(blank=True, max_length=512, verbose_name='Wi-Fi パスワード（暗号化）'),
        ),
        migrations.AddField(
            model_name='media',
            name='cached_thumbnail_url',
            field=models.URLField(blank=True, verbose_name='サムネイルURL'),
        ),
        migrations.AlterField(
            model_name='iotdevice',
            name='external_id',
            field=models.CharField(max_length=255, unique=True, verbose_name='デバイスID（AWS側）'),
        ),
    ]
