# Generated by Django 6.0.1 on 2026-02-21 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0041_property_propertydevice_propertyalert'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='iotevent',
            new_name='booking_iot_device__53b5b5_idx',
            old_name='booking_iot_device__b0e4c9_idx',
        ),
        migrations.RenameIndex(
            model_name='iotevent',
            new_name='booking_iot_device__7d7ed2_idx',
            old_name='booking_iot_device__c1f5da_idx',
        ),
        migrations.RenameIndex(
            model_name='propertyalert',
            new_name='booking_pro_propert_5ce5d2_idx',
            old_name='booking_pro_propert_a1b2c3_idx',
        ),
        migrations.RenameIndex(
            model_name='propertyalert',
            new_name='booking_pro_alert_t_52d60c_idx',
            old_name='booking_pro_alert_t_d4e5f6_idx',
        ),
        migrations.AddField(
            model_name='staff',
            name='is_owner',
            field=models.BooleanField(default=False, verbose_name='オーナー'),
        ),
    ]
