# Generated by Django 6.0.1 on 2026-02-21 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0042_rename_booking_iot_device__b0e4c9_idx_booking_iot_device__53b5b5_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='booking_channel',
            field=models.CharField(choices=[('line', 'LINE'), ('email', 'Email')], default='line', max_length=10, verbose_name='予約経路'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='顧客メール'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='email_otp_expires',
            field=models.DateTimeField(blank=True, null=True, verbose_name='OTP有効期限'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='email_otp_hash',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='OTPハッシュ'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='email_verified',
            field=models.BooleanField(default=False, verbose_name='メール認証済み'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='payment_url',
            field=models.URLField(blank=True, null=True, verbose_name='決済URL'),
        ),
        migrations.AddField(
            model_name='staff',
            name='staff_type',
            field=models.CharField(choices=[('fortune_teller', '占い師'), ('store_staff', '店舗スタッフ')], db_index=True, default='fortune_teller', max_length=20, verbose_name='スタッフ種別'),
        ),
        migrations.CreateModel(
            name='DashboardLayout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layout_json', models.JSONField(default=list, verbose_name='レイアウトJSON')),
                ('dark_mode', models.BooleanField(default=False, verbose_name='ダークモード')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_layout', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ダッシュボードレイアウト',
                'verbose_name_plural': 'ダッシュボードレイアウト',
            },
        ),
    ]
