# Generated by Django 5.2.9 on 2026-02-21 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0043_staff_type_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminTheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_color', models.CharField(default='#8c876c', max_length=7, verbose_name='メインカラー')),
                ('secondary_color', models.CharField(default='#f1f0ec', max_length=7, verbose_name='サブカラー')),
                ('header_image', models.ImageField(blank=True, upload_to='admin_themes/', verbose_name='ヘッダー画像')),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_theme', to='booking.store')),
            ],
            options={
                'verbose_name': '管理画面テーマ',
                'verbose_name_plural': '管理画面テーマ',
            },
        ),
        migrations.CreateModel(
            name='ShiftPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_month', models.DateField(verbose_name='対象年月')),
                ('deadline', models.DateTimeField(verbose_name='申請締切')),
                ('status', models.CharField(choices=[('open', '募集中'), ('closed', '締切'), ('scheduled', 'スケジュール済'), ('approved', '承認済')], default='open', max_length=20, verbose_name='状態')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.staff')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_periods', to='booking.store')),
            ],
            options={
                'verbose_name': 'シフト募集期間',
                'verbose_name_plural': 'シフト募集期間',
            },
        ),
        migrations.CreateModel(
            name='StoreScheduleConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_hour', models.IntegerField(default=9, verbose_name='営業開始時間')),
                ('close_hour', models.IntegerField(default=21, verbose_name='営業終了時間')),
                ('slot_duration', models.IntegerField(default=60, help_text='15, 30, 45, 60 のいずれか', verbose_name='予約コマ(分)')),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_config', to='booking.store')),
            ],
            options={
                'verbose_name': '店舗スケジュール設定',
                'verbose_name_plural': '店舗スケジュール設定',
            },
        ),
        migrations.CreateModel(
            name='ShiftAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日付')),
                ('start_hour', models.IntegerField(verbose_name='開始時間')),
                ('end_hour', models.IntegerField(verbose_name='終了時間')),
                ('is_synced', models.BooleanField(default=False, verbose_name='Schedule同期済み')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_assignments', to='booking.staff')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='booking.shiftperiod')),
            ],
            options={
                'verbose_name': '確定シフト',
                'verbose_name_plural': '確定シフト',
                'unique_together': {('period', 'staff', 'date', 'start_hour')},
            },
        ),
        migrations.CreateModel(
            name='ShiftRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日付')),
                ('start_hour', models.IntegerField(verbose_name='開始時間')),
                ('end_hour', models.IntegerField(verbose_name='終了時間')),
                ('preference', models.CharField(choices=[('available', '出勤可能'), ('preferred', '希望'), ('unavailable', '出勤不可')], default='available', max_length=20, verbose_name='希望区分')),
                ('note', models.TextField(blank=True, verbose_name='備考')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='booking.shiftperiod')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_requests', to='booking.staff')),
            ],
            options={
                'verbose_name': 'シフト希望',
                'verbose_name_plural': 'シフト希望',
                'unique_together': {('period', 'staff', 'date', 'start_hour')},
            },
        ),
    ]
