# Generated by Django 4.2.25 on 2026-02-21 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0044_shift_management'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_ec_visible',
            field=models.BooleanField(db_index=True, default=False, help_text='チェックするとオンラインショップに表示されます', verbose_name='EC公開'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='checked_in_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='チェックイン日時'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='checkin_qr',
            field=models.ImageField(blank=True, null=True, upload_to='checkin_qr/', verbose_name='チェックインQR'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='is_checked_in',
            field=models.BooleanField(default=False, verbose_name='チェックイン済み'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(db_index=True, max_length=64, verbose_name='商品コード'),
        ),
    ]
