# Generated by Django 4.2.25 on 2026-02-22 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0045_product_ec_schedule_checkin'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageCustomBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('content', models.TextField(help_text='HTMLを直接記述できます', verbose_name='HTML内容')),
                ('position', models.CharField(choices=[('above_cards', 'カードの上'), ('below_cards', 'カードの下'), ('sidebar', 'サイドバー')], default='below_cards', max_length=20, verbose_name='表示位置')),
                ('sort_order', models.IntegerField(default=0, verbose_name='並び順')),
                ('is_active', models.BooleanField(default=True, verbose_name='公開')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'カスタムブロック',
                'verbose_name_plural': 'カスタムブロック',
                'ordering': ['position', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='占いサロンチャンス', max_length=200, verbose_name='サイト名')),
                ('show_card_store', models.BooleanField(default=True, verbose_name='店舗カード表示')),
                ('show_card_fortune_teller', models.BooleanField(default=True, verbose_name='占い師カード表示')),
                ('show_card_calendar', models.BooleanField(default=True, verbose_name='カレンダーカード表示')),
                ('show_card_shop', models.BooleanField(default=True, verbose_name='ショップカード表示')),
                ('show_sidebar_notice', models.BooleanField(default=True, verbose_name='お知らせ表示')),
                ('show_sidebar_company', models.BooleanField(default=True, verbose_name='運営会社表示')),
                ('show_sidebar_media', models.BooleanField(default=True, verbose_name='メディア掲載表示')),
                ('show_sidebar_social', models.BooleanField(default=False, verbose_name='SNSフィード表示')),
                ('twitter_url', models.URLField(blank=True, default='', help_text='例: https://twitter.com/youraccount', verbose_name='X(Twitter) URL')),
                ('instagram_url', models.URLField(blank=True, default='', help_text='例: https://www.instagram.com/youraccount', verbose_name='Instagram URL')),
            ],
            options={
                'verbose_name': 'サイト設定',
                'verbose_name_plural': 'サイト設定',
            },
        ),
    ]
