# Generated by Django 4.2.25 on 2026-02-22 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0046_homepagecustomblock_sitesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerAd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('image', models.ImageField(upload_to='banner_ads/', verbose_name='バナー画像')),
                ('link_url', models.URLField(blank=True, default='', verbose_name='リンクURL')),
                ('position', models.CharField(choices=[('after_hero', 'ヒーローバナーの後'), ('after_cards', 'カードの後'), ('after_ranking', 'ランキングの後'), ('after_campaign', 'キャンペーンの後'), ('sidebar', 'サイドバー')], default='after_hero', max_length=20, verbose_name='表示位置')),
                ('sort_order', models.IntegerField(default=0, verbose_name='並び順')),
                ('is_active', models.BooleanField(default=True, verbose_name='公開')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'バナー広告',
                'verbose_name_plural': 'バナー広告',
                'ordering': ['position', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ExternalLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('url', models.URLField(verbose_name='URL')),
                ('description', models.TextField(blank=True, default='', verbose_name='説明')),
                ('sort_order', models.IntegerField(default=0, verbose_name='並び順')),
                ('is_active', models.BooleanField(default=True, verbose_name='公開')),
                ('open_in_new_tab', models.BooleanField(default=True, verbose_name='新しいタブで開く')),
            ],
            options={
                'verbose_name': '外部リンク',
                'verbose_name_plural': '外部リンク',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='HeroBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('image', models.ImageField(upload_to='hero_banners/', verbose_name='バナー画像')),
                ('link_url', models.URLField(blank=True, default='', verbose_name='リンクURL')),
                ('sort_order', models.IntegerField(default=0, verbose_name='並び順')),
                ('is_active', models.BooleanField(default=True, verbose_name='公開')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'ヒーローバナー',
                'verbose_name_plural': 'ヒーローバナー',
                'ordering': ['sort_order'],
            },
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='instagram_embed_html',
            field=models.TextField(blank=True, default='', help_text='Instagramの投稿埋め込みHTMLを貼り付けてください', verbose_name='Instagram埋め込みHTML'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='ranking_limit',
            field=models.IntegerField(default=5, verbose_name='ランキング表示件数'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='show_hero_banner',
            field=models.BooleanField(default=True, verbose_name='ヒーローバナー表示'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='show_ranking',
            field=models.BooleanField(default=True, verbose_name='予約ランキング表示'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='show_sidebar_external_links',
            field=models.BooleanField(default=True, verbose_name='外部リンク表示'),
        ),
    ]
