# Generated by Django 4.2.25 on 2026-02-22 04:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0047_bannerad_externallink_herobanner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminMenuConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('developer', '開発者'), ('owner', 'オーナー'), ('manager', '店長'), ('staff', 'スタッフ')], help_text='superuserは常に全モデルを表示するため設定不要', max_length=20, unique=True, verbose_name='ロール')),
                ('allowed_models', models.JSONField(default=list, verbose_name='表示許可モデル')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
            ],
            options={
                'verbose_name': 'メニュー権限設定',
                'verbose_name_plural': 'メニュー権限設定',
            },
        ),
    ]
