# Generated by Django 4.2.25 on 2026-02-22 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0048_adminmenuconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmploymentContract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employment_type', models.CharField(choices=[('full_time', '正社員'), ('part_time', 'パート・アルバイト'), ('contract', '契約社員')], default='part_time', max_length=20, verbose_name='雇用形態')),
                ('pay_type', models.CharField(choices=[('hourly', '時給'), ('monthly', '月給')], default='hourly', max_length=10, verbose_name='給与形態')),
                ('hourly_rate', models.IntegerField(default=0, help_text='時給制の場合に設定', verbose_name='時給（円）')),
                ('monthly_salary', models.IntegerField(default=0, help_text='月給制の場合に設定', verbose_name='月給（円）')),
                ('commute_allowance', models.IntegerField(default=0, verbose_name='通勤手当（円/月）')),
                ('housing_allowance', models.IntegerField(default=0, verbose_name='住宅手当（円/月）')),
                ('family_allowance', models.IntegerField(default=0, verbose_name='家族手当（円/月）')),
                ('standard_monthly_remuneration', models.IntegerField(default=0, help_text='社会保険料計算の基準額。4〜6月の平均報酬から算定。', verbose_name='標準報酬月額（円）')),
                ('resident_tax_monthly', models.IntegerField(default=0, help_text='特別徴収の月額', verbose_name='住民税月額（円）')),
                ('birth_date', models.DateField(blank=True, help_text='介護保険適用判定に使用（40歳以上）', null=True, verbose_name='生年月日')),
                ('contract_start', models.DateField(blank=True, null=True, verbose_name='契約開始日')),
                ('contract_end', models.DateField(blank=True, null=True, verbose_name='契約終了日')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employment_contract', to='booking.staff', verbose_name='スタッフ')),
            ],
            options={
                'verbose_name': '雇用契約',
                'verbose_name_plural': '雇用契約',
            },
        ),
        migrations.CreateModel(
            name='SalaryStructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pension_rate', models.DecimalField(decimal_places=3, default=9.15, help_text='従業員負担分 例: 9.150', max_digits=5, verbose_name='厚生年金料率(%)')),
                ('health_insurance_rate', models.DecimalField(decimal_places=3, default=5.0, help_text='従業員負担分 例: 5.000（協会けんぽ東京支部）', max_digits=5, verbose_name='健康保険料率(%)')),
                ('employment_insurance_rate', models.DecimalField(decimal_places=3, default=0.6, help_text='従業員負担分 例: 0.600', max_digits=5, verbose_name='雇用保険料率(%)')),
                ('long_term_care_rate', models.DecimalField(decimal_places=3, default=0.82, help_text='40歳以上のみ適用 例: 0.820', max_digits=5, verbose_name='介護保険料率(%)')),
                ('workers_comp_rate', models.DecimalField(decimal_places=3, default=0.3, help_text='事業主全額負担（記録用） 例: 0.300', max_digits=5, verbose_name='労災保険料率(%)')),
                ('overtime_multiplier', models.DecimalField(decimal_places=2, default=1.25, max_digits=4, verbose_name='残業割増率')),
                ('late_night_multiplier', models.DecimalField(decimal_places=2, default=1.35, max_digits=4, verbose_name='深夜割増率')),
                ('holiday_multiplier', models.DecimalField(decimal_places=2, default=1.5, max_digits=4, verbose_name='休日割増率')),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salary_structure', to='booking.store', verbose_name='店舗')),
            ],
            options={
                'verbose_name': '給与体系',
                'verbose_name_plural': '給与体系',
            },
        ),
        migrations.CreateModel(
            name='PayrollPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_month', models.CharField(help_text='YYYY-MM形式', max_length=7, verbose_name='対象年月')),
                ('period_start', models.DateField(verbose_name='計算期間開始')),
                ('period_end', models.DateField(verbose_name='計算期間終了')),
                ('status', models.CharField(choices=[('draft', '下書き'), ('calculating', '計算中'), ('confirmed', '確定'), ('paid', '支払済')], default='draft', max_length=20, verbose_name='状態')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='支給日')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_periods', to='booking.store', verbose_name='店舗')),
            ],
            options={
                'verbose_name': '給与計算期間',
                'verbose_name_plural': '給与計算期間',
                'unique_together': {('store', 'year_month')},
            },
        ),
        migrations.CreateModel(
            name='PayrollEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_work_days', models.IntegerField(default=0, verbose_name='出勤日数')),
                ('total_regular_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='通常勤務時間')),
                ('total_overtime_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='残業時間')),
                ('total_late_night_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='深夜勤務時間')),
                ('total_holiday_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='休日勤務時間')),
                ('base_pay', models.IntegerField(default=0, verbose_name='基本給')),
                ('overtime_pay', models.IntegerField(default=0, verbose_name='残業手当')),
                ('late_night_pay', models.IntegerField(default=0, verbose_name='深夜手当')),
                ('holiday_pay', models.IntegerField(default=0, verbose_name='休日手当')),
                ('allowances', models.IntegerField(default=0, help_text='通勤+住宅+家族手当', verbose_name='各種手当合計')),
                ('gross_pay', models.IntegerField(default=0, verbose_name='総支給額')),
                ('total_deductions', models.IntegerField(default=0, verbose_name='控除合計')),
                ('net_pay', models.IntegerField(default=0, verbose_name='差引支給額')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_entries', to='booking.employmentcontract', verbose_name='雇用契約')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='booking.payrollperiod', verbose_name='給与期間')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_entries', to='booking.staff', verbose_name='スタッフ')),
            ],
            options={
                'verbose_name': '給与明細',
                'verbose_name_plural': '給与明細',
                'unique_together': {('period', 'staff')},
            },
        ),
        migrations.CreateModel(
            name='PayrollDeduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deduction_type', models.CharField(choices=[('income_tax', '所得税（源泉徴収）'), ('resident_tax', '住民税'), ('pension', '厚生年金'), ('health_insurance', '健康保険'), ('employment_insurance', '雇用保険'), ('long_term_care', '介護保険'), ('workers_comp', '労災保険'), ('other', 'その他')], max_length=30, verbose_name='控除種別')),
                ('amount', models.IntegerField(default=0, verbose_name='金額')),
                ('is_employer_only', models.BooleanField(default=False, help_text='労災保険等、従業員控除なし', verbose_name='事業主負担のみ')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deductions', to='booking.payrollentry', verbose_name='給与明細')),
            ],
            options={
                'verbose_name': '控除明細',
                'verbose_name_plural': '控除明細',
            },
        ),
        migrations.CreateModel(
            name='WorkAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='日付')),
                ('clock_in', models.TimeField(blank=True, null=True, verbose_name='出勤時刻')),
                ('clock_out', models.TimeField(blank=True, null=True, verbose_name='退勤時刻')),
                ('regular_minutes', models.IntegerField(default=0, verbose_name='通常勤務（分）')),
                ('overtime_minutes', models.IntegerField(default=0, verbose_name='残業（分）')),
                ('late_night_minutes', models.IntegerField(default=0, verbose_name='深夜勤務（分）')),
                ('holiday_minutes', models.IntegerField(default=0, verbose_name='休日勤務（分）')),
                ('break_minutes', models.IntegerField(default=0, verbose_name='休憩（分）')),
                ('source', models.CharField(choices=[('shift', 'シフトから自動生成'), ('manual', '手動入力'), ('corrected', '修正済み')], default='shift', max_length=20, verbose_name='データソース')),
                ('source_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_attendances', to='booking.shiftassignment', verbose_name='元シフト')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='booking.staff', verbose_name='スタッフ')),
            ],
            options={
                'verbose_name': '勤怠記録',
                'verbose_name_plural': '勤怠記録',
                'indexes': [models.Index(fields=['staff', 'date'], name='booking_wor_staff_i_d06479_idx'), models.Index(fields=['date'], name='booking_wor_date_71a748_idx')],
                'unique_together': {('staff', 'date')},
            },
        ),
    ]
