# Generated by Django 4.2.25 on 2026-02-22 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0049_employmentcontract_salarystructure_payrollperiod_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='herobanner',
            name='image_position',
            field=models.CharField(choices=[('center', '中央'), ('top', '上'), ('bottom', '下'), ('left', '左'), ('right', '右'), ('top left', '左上'), ('top right', '右上'), ('bottom left', '左下'), ('bottom right', '右下')], default='center', help_text='バナー内で画像のどの部分を表示するかを指定します', max_length=20, verbose_name='画像表示位置'),
        ),
    ]
