# Generated by Django 4.2.25 on 2026-02-22 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0050_add_herobanner_image_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='herobanner',
            name='link_type',
            field=models.CharField(choices=[('none', 'リンクなし'), ('store', '店舗'), ('staff', '占い師'), ('url', 'カスタムURL')], default='none', max_length=10, verbose_name='リンク種別'),
        ),
        migrations.AddField(
            model_name='herobanner',
            name='linked_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.staff', verbose_name='リンク先占い師'),
        ),
        migrations.AddField(
            model_name='herobanner',
            name='linked_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.store', verbose_name='リンク先店舗'),
        ),
        migrations.AddField(
            model_name='staff',
            name='is_recommended',
            field=models.BooleanField(default=False, verbose_name='おすすめ'),
        ),
        migrations.AddField(
            model_name='store',
            name='is_recommended',
            field=models.BooleanField(default=False, verbose_name='おすすめ'),
        ),
    ]
