# Generated by Django 4.2.25 on 2026-02-23 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0051_herobanner_link_type_herobanner_linked_staff_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name': 'キャスト', 'verbose_name_plural': 'キャスト'},
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='staff_label',
            field=models.CharField(default='キャスト', help_text='管理画面・フロントで「占い師」「スタッフ」の代わりに表示する名称（例: キャスト、セラピスト）', max_length=50, verbose_name='スタッフの呼称'),
        ),
    ]
