# Generated by Django 4.2.25 on 2026-02-23 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0052_add_staff_label_to_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='privacy_policy_html',
            field=models.TextField(blank=True, default='', help_text='HTMLで記述。空の場合はデフォルトテンプレートが表示されます。', verbose_name='プライバシーポリシー'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tokushoho_html',
            field=models.TextField(blank=True, default='', help_text='HTMLで記述。空の場合はデフォルトテンプレートが表示されます。', verbose_name='特定商取引法に基づく表記'),
        ),
    ]
