# Generated by Django 5.2.9 on 2026-02-23 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0053_add_legal_pages_to_sitesettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name': 'キャスト', 'verbose_name_plural': 'キャスト一覧'},
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='show_ai_chat',
            field=models.BooleanField(default=False, help_text='フロントページにAIアシスタントチャットを表示するかどうか', verbose_name='AIアシスタント表示'),
        ),
    ]
