# Generated by Django 4.2.25 on 2026-02-23 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0054_add_show_ai_chat_to_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='iotdevice',
            name='alert_line_user_id',
            field=models.CharField(blank=True, default='', help_text='閾値超過時にLINE通知を送信するユーザーID', max_length=255, verbose_name='アラートLINE通知先ID'),
        ),
        migrations.AddField(
            model_name='iotdevice',
            name='pending_ir_command',
            field=models.TextField(blank=True, default='', help_text='デバイスが次回config取得時に実行するIRコマンド（JSON）', verbose_name='保留中IRコマンド'),
        ),
        migrations.CreateModel(
            name='IRCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名前')),
                ('protocol', models.CharField(default='NEC', max_length=20, verbose_name='プロトコル')),
                ('code', models.CharField(max_length=20, verbose_name='コード')),
                ('address', models.CharField(blank=True, default='', max_length=20, verbose_name='アドレス')),
                ('command', models.CharField(blank=True, default='', max_length=20, verbose_name='コマンド')),
                ('raw_data', models.TextField(blank=True, default='', verbose_name='RAWデータ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ir_codes', to='booking.iotdevice', verbose_name='デバイス')),
            ],
            options={
                'verbose_name': 'IRコード',
                'verbose_name_plural': 'IRコード',
            },
        ),
    ]
