# Generated by Django 6.0.1 on 2026-02-23 13:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0055_iotdevice_alert_line_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/', verbose_name='商品画像'),
        ),
        migrations.CreateModel(
            name='TableSeat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(help_text='例: A1, テーブル1, カウンター3', max_length=50, verbose_name='席名')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='table_qr/', verbose_name='QRコード画像')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_seats', to='booking.store', verbose_name='店舗')),
            ],
            options={
                'verbose_name': 'テーブル/席',
                'verbose_name_plural': 'テーブル/席',
                'ordering': ('store', 'label'),
                'unique_together': {('store', 'label')},
            },
        ),
        migrations.AddField(
            model_name='order',
            name='table_seat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='booking.tableseat', verbose_name='席'),
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_type', models.CharField(choices=[('cash', '現金'), ('coiney', 'Coiney (クレジットカード)'), ('paypay', 'PayPay'), ('ic', 'IC決済 (交通系/電子マネー)'), ('other', 'その他')], max_length=20, verbose_name='決済種別')),
                ('display_name', models.CharField(max_length=100, verbose_name='表示名')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='有効')),
                ('api_key', models.CharField(blank=True, default='', max_length=500, verbose_name='APIキー')),
                ('api_secret', models.CharField(blank=True, default='', max_length=500, verbose_name='APIシークレット')),
                ('api_endpoint', models.URLField(blank=True, default='', verbose_name='APIエンドポイント')),
                ('extra_config', models.JSONField(blank=True, default=dict, verbose_name='追加設定')),
                ('sort_order', models.IntegerField(default=0, verbose_name='並び順')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='booking.store', verbose_name='店舗')),
            ],
            options={
                'verbose_name': '決済方法',
                'verbose_name_plural': '決済方法',
                'ordering': ('store', 'sort_order'),
                'unique_together': {('store', 'method_type')},
            },
        ),
    ]
