# Generated by Django 4.2.25 on 2026-03-05 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0056_product_image_tableseat_order_table_seat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.UUIDField(db_index=True, default=uuid.uuid4, verbose_name='実行ID')),
                ('check_name', models.CharField(max_length=100, verbose_name='チェック名')),
                ('resource_type', models.CharField(choices=[('ec2', 'EC2'), ('s3', 'S3'), ('ebs', 'EBS'), ('eip', 'Elastic IP'), ('rds', 'RDS'), ('total', '合計')], max_length=10, verbose_name='リソース種別')),
                ('resource_id', models.CharField(blank=True, default='', max_length=200, verbose_name='リソースID')),
                ('status', models.CharField(choices=[('ok', 'OK'), ('warn', '警告'), ('alert', 'アラート')], max_length=10, verbose_name='状態')),
                ('estimated_monthly_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='推定月額コスト')),
                ('detail', models.TextField(blank=True, default='', verbose_name='詳細')),
                ('recommendation', models.TextField(blank=True, default='', verbose_name='推奨事項')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='実行日時')),
            ],
            options={
                'verbose_name': 'AWSコストレポート',
                'verbose_name_plural': 'AWSコストレポート',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SecurityAudit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.UUIDField(db_index=True, default=uuid.uuid4, verbose_name='実行ID')),
                ('check_name', models.CharField(max_length=100, verbose_name='チェック名')),
                ('category', models.CharField(choices=[('django_settings', 'Django設定'), ('credentials', '認証情報'), ('endpoints', 'エンドポイント'), ('infrastructure', 'インフラ'), ('dependencies', '依存関係')], max_length=30, verbose_name='カテゴリ')),
                ('severity', models.CharField(choices=[('critical', '重大'), ('high', '高'), ('medium', '中'), ('low', '低'), ('info', '情報'), ('pass', '合格')], max_length=10, verbose_name='重大度')),
                ('status', models.CharField(choices=[('fail', '不合格'), ('warn', '警告'), ('pass', '合格')], max_length=10, verbose_name='結果')),
                ('message', models.TextField(verbose_name='メッセージ')),
                ('recommendation', models.TextField(blank=True, default='', verbose_name='推奨事項')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='実行日時')),
            ],
            options={
                'verbose_name': 'セキュリティ監査',
                'verbose_name_plural': 'セキュリティ監査',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SecurityLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('login_success', 'ログイン成功'), ('login_fail', 'ログイン失敗'), ('api_auth_fail', 'API認証失敗'), ('permission_denied', '権限拒否'), ('suspicious_request', '不審なリクエスト'), ('admin_action', '管理操作')], db_index=True, max_length=30, verbose_name='イベント種別')),
                ('severity', models.CharField(choices=[('critical', '緊急'), ('warning', '警告'), ('info', '情報')], default='info', max_length=10, verbose_name='重要度')),
                ('username', models.CharField(blank=True, default='', max_length=150, verbose_name='ユーザー名')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IPアドレス')),
                ('user_agent', models.TextField(blank=True, default='', verbose_name='User-Agent')),
                ('path', models.CharField(blank=True, default='', max_length=500, verbose_name='パス')),
                ('method', models.CharField(blank=True, default='', max_length=10, verbose_name='メソッド')),
                ('detail', models.TextField(blank=True, default='', verbose_name='詳細')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='発生日時')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'セキュリティログ',
                'verbose_name_plural': 'セキュリティログ',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', 'created_at'], name='booking_sec_event_t_339728_idx'), models.Index(fields=['ip_address', 'created_at'], name='booking_sec_ip_addr_1636fa_idx')],
            },
        ),
    ]
