# Generated by Django 4.2.25 on 2026-03-09 06:33

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0057_costreport_securityaudit_securitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.IntegerField(default=0, verbose_name='割引額'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', '未払い'), ('partial', '一部支払'), ('paid', '支払済'), ('refunded', '返金済')], default='pending', max_length=20, verbose_name='支払状態'),
        ),
        migrations.AddField(
            model_name='order',
            name='tax_amount',
            field=models.IntegerField(default=0, verbose_name='税額'),
        ),
        migrations.AddField(
            model_name='shiftassignment',
            name='color',
            field=models.CharField(default='#3B82F6', max_length=7, verbose_name='表示色'),
        ),
        migrations.AddField(
            model_name='shiftassignment',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='終了時刻'),
        ),
        migrations.AddField(
            model_name='shiftassignment',
            name='note',
            field=models.TextField(blank=True, default='', verbose_name='備考'),
        ),
        migrations.AddField(
            model_name='shiftassignment',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='開始時刻'),
        ),
        migrations.AddField(
            model_name='shiftrequest',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='終了時刻'),
        ),
        migrations.AddField(
            model_name='shiftrequest',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='開始時刻'),
        ),
        migrations.AddField(
            model_name='workattendance',
            name='qr_clock_in',
            field=models.DateTimeField(blank=True, null=True, verbose_name='QR出勤日時'),
        ),
        migrations.AddField(
            model_name='workattendance',
            name='qr_clock_out',
            field=models.DateTimeField(blank=True, null=True, verbose_name='QR退勤日時'),
        ),
        migrations.AlterField(
            model_name='salarystructure',
            name='employment_insurance_rate',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.600'), help_text='従業員負担分 例: 0.600', max_digits=5, verbose_name='雇用保険料率(%)'),
        ),
        migrations.AlterField(
            model_name='salarystructure',
            name='late_night_multiplier',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.35'), max_digits=4, verbose_name='深夜割増率'),
        ),
        migrations.AlterField(
            model_name='salarystructure',
            name='long_term_care_rate',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.820'), help_text='40歳以上のみ適用 例: 0.820', max_digits=5, verbose_name='介護保険料率(%)'),
        ),
        migrations.AlterField(
            model_name='salarystructure',
            name='pension_rate',
            field=models.DecimalField(decimal_places=3, default=Decimal('9.150'), help_text='従業員負担分 例: 9.150', max_digits=5, verbose_name='厚生年金料率(%)'),
        ),
        migrations.AlterField(
            model_name='salarystructure',
            name='workers_comp_rate',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.300'), help_text='事業主全額負担（記録用） 例: 0.300', max_digits=5, verbose_name='労災保険料率(%)'),
        ),
        migrations.AlterField(
            model_name='workattendance',
            name='source',
            field=models.CharField(choices=[('shift', 'シフトから自動生成'), ('manual', '手動入力'), ('corrected', '修正済み'), ('qr', 'QR打刻')], default='shift', max_length=20, verbose_name='データソース'),
        ),
        migrations.CreateModel(
            name='VisitorAnalyticsConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_gap_seconds', models.IntegerField(default=300, help_text='この秒数以内の連続検知は同一来客とカウント', verbose_name='セッション間隔(秒)')),
                ('pir_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.iotdevice', verbose_name='PIRデバイス')),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='visitor_config', to='booking.store', verbose_name='店舗')),
            ],
            options={
                'verbose_name': '来客分析設定',
                'verbose_name_plural': '来客分析設定',
            },
        ),
        migrations.CreateModel(
            name='StaffRecommendationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_file', models.FileField(upload_to='ml_models/', verbose_name='モデルファイル')),
                ('model_type', models.CharField(default='random_forest', max_length=50, verbose_name='モデル種別')),
                ('feature_names', models.JSONField(default=list, verbose_name='特徴量名')),
                ('accuracy_score', models.FloatField(default=0, verbose_name='精度スコア')),
                ('mae_score', models.FloatField(default=0, verbose_name='MAEスコア')),
                ('training_samples', models.IntegerField(default=0, verbose_name='学習サンプル数')),
                ('trained_at', models.DateTimeField(auto_now_add=True, verbose_name='学習日時')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_models', to='booking.store', verbose_name='店舗')),
            ],
            options={
                'verbose_name': 'AI推薦モデル',
                'verbose_name_plural': 'AI推薦モデル',
                'ordering': ('-trained_at',),
            },
        ),
        migrations.CreateModel(
            name='ShiftTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='テンプレート名')),
                ('start_time', models.TimeField(verbose_name='開始時刻')),
                ('end_time', models.TimeField(verbose_name='終了時刻')),
                ('color', models.CharField(default='#3B82F6', max_length=7, verbose_name='表示色')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('sort_order', models.IntegerField(default=0, verbose_name='並び順')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_templates', to='booking.store', verbose_name='店舗')),
            ],
            options={
                'verbose_name': 'シフトテンプレート',
                'verbose_name_plural': 'シフトテンプレート',
                'ordering': ('store', 'sort_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='ShiftPublishHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='公開日時')),
                ('assignment_count', models.IntegerField(default=0, verbose_name='シフト数')),
                ('note', models.TextField(blank=True, default='', verbose_name='備考')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publish_history', to='booking.shiftperiod', verbose_name='シフト期間')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.staff', verbose_name='公開者')),
            ],
            options={
                'verbose_name': 'シフト公開履歴',
                'verbose_name_plural': 'シフト公開履歴',
                'ordering': ('-published_at',),
            },
        ),
        migrations.CreateModel(
            name='AttendanceTOTPConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totp_secret', models.CharField(max_length=64, verbose_name='TOTPシークレット')),
                ('totp_interval', models.IntegerField(default=30, verbose_name='TOTP間隔(秒)')),
                ('location_lat', models.FloatField(blank=True, null=True, verbose_name='緯度')),
                ('location_lng', models.FloatField(blank=True, null=True, verbose_name='経度')),
                ('geo_fence_radius_m', models.IntegerField(default=200, verbose_name='ジオフェンス半径(m)')),
                ('require_geo_check', models.BooleanField(default=False, verbose_name='位置確認必須')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='totp_config', to='booking.store', verbose_name='店舗')),
            ],
            options={
                'verbose_name': 'TOTP勤怠設定',
                'verbose_name_plural': 'TOTP勤怠設定',
            },
        ),
        migrations.CreateModel(
            name='VisitorCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='日付')),
                ('hour', models.IntegerField(verbose_name='時間帯')),
                ('pir_count', models.IntegerField(default=0, verbose_name='PIR検知数')),
                ('estimated_visitors', models.IntegerField(default=0, verbose_name='推定来客数')),
                ('order_count', models.IntegerField(default=0, verbose_name='注文数')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitor_counts', to='booking.store', verbose_name='店舗')),
            ],
            options={
                'verbose_name': '来客数',
                'verbose_name_plural': '来客数',
                'indexes': [models.Index(fields=['store', 'date'], name='booking_vis_store_i_1cdcf0_idx')],
                'unique_together': {('store', 'date', 'hour')},
            },
        ),
        migrations.CreateModel(
            name='StaffRecommendationResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日付')),
                ('hour', models.IntegerField(verbose_name='時間帯')),
                ('recommended_staff_count', models.IntegerField(verbose_name='推薦スタッフ数')),
                ('confidence', models.FloatField(default=0, verbose_name='信頼度')),
                ('factors', models.JSONField(default=dict, verbose_name='特徴量重要度')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_results', to='booking.store', verbose_name='店舗')),
            ],
            options={
                'verbose_name': 'AI推薦結果',
                'verbose_name_plural': 'AI推薦結果',
                'unique_together': {('store', 'date', 'hour')},
            },
        ),
        migrations.CreateModel(
            name='POSTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.IntegerField(default=0, verbose_name='合計金額')),
                ('tax_amount', models.IntegerField(default=0, verbose_name='税額')),
                ('discount_amount', models.IntegerField(default=0, verbose_name='割引額')),
                ('cash_received', models.IntegerField(blank=True, null=True, verbose_name='受取金額')),
                ('change_given', models.IntegerField(blank=True, null=True, verbose_name='お釣り')),
                ('receipt_number', models.CharField(max_length=20, unique=True, verbose_name='レシート番号')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完了日時')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pos_transaction', to='booking.order', verbose_name='注文')),
                ('payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.paymentmethod', verbose_name='決済方法')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.staff', verbose_name='担当')),
            ],
            options={
                'verbose_name': 'POS決済',
                'verbose_name_plural': 'POS決済',
                'indexes': [models.Index(fields=['receipt_number'], name='booking_pos_receipt_3fc8b5_idx'), models.Index(fields=['completed_at'], name='booking_pos_complet_fde123_idx')],
            },
        ),
        migrations.CreateModel(
            name='AttendanceStamp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stamp_type', models.CharField(choices=[('clock_in', '出勤'), ('clock_out', '退勤'), ('break_start', '休憩開始'), ('break_end', '休憩終了')], max_length=20, verbose_name='打刻種別')),
                ('stamped_at', models.DateTimeField(auto_now_add=True, verbose_name='打刻日時')),
                ('totp_used', models.CharField(blank=True, default='', max_length=10, verbose_name='使用TOTP')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IPアドレス')),
                ('user_agent', models.TextField(blank=True, default='', verbose_name='User-Agent')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='緯度')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='経度')),
                ('is_valid', models.BooleanField(default=True, verbose_name='有効')),
                ('invalidation_reason', models.CharField(blank=True, default='', max_length=100, verbose_name='無効理由')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_stamps', to='booking.staff', verbose_name='スタッフ')),
            ],
            options={
                'verbose_name': '打刻ログ',
                'verbose_name_plural': '打刻ログ',
                'ordering': ('-stamped_at',),
                'indexes': [models.Index(fields=['staff', 'stamped_at'], name='booking_att_staff_i_b4d47f_idx'), models.Index(fields=['stamp_type', 'stamped_at'], name='booking_att_stamp_t_213a44_idx')],
            },
        ),
    ]
