# Generated by Django 4.2.25 on 2026-03-09 12:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0058_order_discount_amount_order_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminmenuconfig',
            options={'verbose_name': '権限設定', 'verbose_name_plural': '権限設定'},
        ),
        migrations.AlterModelOptions(
            name='iotdevice',
            options={'verbose_name': '店舗センサー', 'verbose_name_plural': '店舗センサー'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': '注文履歴', 'verbose_name_plural': '注文履歴'},
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'verbose_name': '予約確定済みのスケジュール', 'verbose_name_plural': '確定予約一覧'},
        ),
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'メインサイト設定', 'verbose_name_plural': 'メインサイト設定'},
        ),
        migrations.AlterModelOptions(
            name='tableseat',
            options={'ordering': ('store', 'label'), 'verbose_name': 'テーブルQR登録・管理', 'verbose_name_plural': 'テーブルQR登録・管理'},
        ),
        migrations.AddField(
            model_name='staff',
            name='attendance_pin',
            field=models.CharField(blank=True, default='', help_text='4桁の打刻用PINコード', max_length=4, validators=[django.core.validators.RegexValidator('^\\d{4}$', '4桁の数字を入力してください')], verbose_name='勤怠PIN'),
        ),
    ]
