# Generated by Django 4.2.25 on 2026-03-10 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0059_sidebar_restructure_and_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='staff_label_i18n',
            field=models.JSONField(blank=True, default=dict, help_text='言語コードをキーとした翻訳辞書。例: {"en": "Cast", "ko": "캐스트", "zh-hant": "演員"}。未設定の言語はデフォルト呼称を使用。', verbose_name='スタッフ呼称（多言語）'),
        ),
    ]
