# Generated by Django 4.2.25 on 2026-03-11 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0060_staff_label_i18n'),
    ]

    operations = [
        migrations.CreateModel(
            name='VentilationAutoControl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='換気扇自動制御', max_length=100, verbose_name='ルール名')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('threshold_on', models.IntegerField(default=400, help_text='この値を連続で超えたら換気扇ON', verbose_name='ON閾値（MQ-9 ADC値）')),
                ('threshold_off', models.IntegerField(default=200, help_text='この値以下になったら換気扇OFF', verbose_name='OFF閾値（MQ-9 ADC値）')),
                ('consecutive_count', models.IntegerField(default=3, help_text='ON閾値をこの回数連続で超えたらON実行（20秒間隔×3=約1分）', verbose_name='連続超過回数')),
                ('switchbot_token', models.CharField(max_length=200, verbose_name='SwitchBotトークン')),
                ('switchbot_secret', models.CharField(max_length=200, verbose_name='SwitchBotシークレット')),
                ('switchbot_device_id', models.CharField(help_text='スマートプラグのデバイスID', max_length=100, verbose_name='SwitchBotデバイスID')),
                ('fan_state', models.CharField(choices=[('off', 'OFF'), ('on', 'ON'), ('unknown', '不明')], default='unknown', max_length=10, verbose_name='現在の状態')),
                ('last_on_at', models.DateTimeField(blank=True, null=True, verbose_name='最後にONした日時')),
                ('last_off_at', models.DateTimeField(blank=True, null=True, verbose_name='最後にOFFした日時')),
                ('cooldown_seconds', models.IntegerField(default=60, help_text='ON/OFF切替後、次の切替までの最小待機時間', verbose_name='クールダウン（秒）')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventilation_rules', to='booking.iotdevice', verbose_name='対象デバイス')),
            ],
            options={
                'verbose_name': '換気扇自動制御',
                'verbose_name_plural': '換気扇自動制御',
            },
        ),
    ]
