# Generated by Django 4.2.25 on 2026-03-12 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0061_ventilation_auto_control'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessInsight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('sales', '売上'), ('inventory', '在庫'), ('staffing', 'スタッフ'), ('menu', 'メニュー'), ('customer', '顧客')], max_length=20, verbose_name='カテゴリ')),
                ('severity', models.CharField(choices=[('info', '情報'), ('warning', '注意'), ('critical', '重要')], default='info', max_length=10, verbose_name='重要度')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('message', models.TextField(verbose_name='メッセージ')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='関連データ')),
                ('is_read', models.BooleanField(default=False, verbose_name='既読')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='作成日時')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='booking.store', verbose_name='店舗')),
            ],
            options={
                'verbose_name': 'ビジネスインサイト',
                'verbose_name_plural': 'ビジネスインサイト',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['store', 'category', '-created_at'], name='booking_bus_store_i_557d8d_idx')],
            },
        ),
    ]
