# Generated by Django 4.2.25 on 2026-03-12 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0062_business_insight'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerFeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_hash', models.CharField(blank=True, default='', max_length=64, verbose_name='顧客ハッシュ')),
                ('nps_score', models.IntegerField(help_text='0=推奨しない 〜 10=強く推奨', verbose_name='NPS (0-10)')),
                ('food_rating', models.IntegerField(default=3, verbose_name='料理評価 (1-5)')),
                ('service_rating', models.IntegerField(default=3, verbose_name='サービス評価 (1-5)')),
                ('ambiance_rating', models.IntegerField(default=3, verbose_name='雰囲気評価 (1-5)')),
                ('comment', models.TextField(blank=True, default='', verbose_name='コメント')),
                ('sentiment', models.CharField(blank=True, choices=[('positive', 'ポジティブ'), ('neutral', 'ニュートラル'), ('negative', 'ネガティブ')], default='', max_length=10, verbose_name='感情分析')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='作成日時')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to='booking.order', verbose_name='注文')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='booking.store', verbose_name='店舗')),
            ],
            options={
                'verbose_name': '顧客フィードバック',
                'verbose_name_plural': '顧客フィードバック',
                'ordering': ['-created_at'],
            },
        ),
    ]
