# Generated by Django 4.2.25 on 2026-03-13 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0063_customer_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventilationautocontrol',
            name='switchbot_secret',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='SwitchBotシークレット（暗号化）'),
        ),
        migrations.AlterField(
            model_name='ventilationautocontrol',
            name='switchbot_token',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='SwitchBotトークン（暗号化）'),
        ),
    ]
