# Generated by Django 4.2.25 on 2026-03-13 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0064_switchbot_credential_encryption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='attendance_pin',
            field=models.CharField(blank=True, default='', help_text='4桁の打刻用PINコード（ハッシュ化して保存）', max_length=128, verbose_name='勤怠PIN'),
        ),
    ]
