# Generated by Django 4.2.25 on 2026-03-13 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0065_attendance_pin_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='access_info',
            field=models.TextField(blank=True, default='', verbose_name='アクセス情報'),
        ),
        migrations.AddField(
            model_name='store',
            name='map_url',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='地図URL'),
        ),
    ]
