# Generated by Django 4.2.25 on 2026-03-16 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0066_store_access_info_store_map_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='channel',
            field=models.CharField(choices=[('ec', 'ECショップ'), ('pos', 'POS'), ('table', 'テーブル注文'), ('reservation', '予約')], db_index=True, default='pos', max_length=20, verbose_name='注文チャネル'),
        ),
    ]
