# Generated by Django 4.2.25 on 2026-03-16 02:10

from django.db import migrations


def backfill_channel(apps, schema_editor):
    Order = apps.get_model('booking', 'Order')
    # EC orders: table_label starts with "EC:"
    Order.objects.filter(table_label__startswith='EC:').update(channel='ec')
    # Table orders: has table_seat
    Order.objects.filter(table_seat__isnull=False, channel='pos').update(channel='table')
    # Reservation orders: has schedule
    Order.objects.filter(schedule__isnull=False, channel='pos').update(channel='reservation')
    # Remaining stay as 'pos' (default)


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0067_add_channel_to_order'),
    ]

    operations = [
        migrations.RunPython(backfill_channel, migrations.RunPython.noop),
    ]
