# Generated by Django 4.2.25 on 2026-03-16 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0068_backfill_order_channel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postransaction',
            options={'verbose_name': 'POS決済履歴', 'verbose_name_plural': 'POS決済履歴'},
        ),
    ]
