# Generated by Django 4.2.25 on 2026-03-16 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0069_alter_postransaction_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_restaurant_menu',
            field=models.BooleanField(default=True, help_text='チェックを外すとテーブル注文メニューに表示されません（ECのみ等）', verbose_name='飲食メニュー表示'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='price_label',
            field=models.CharField(default='鑑定料', help_text='スタッフ一覧で表示する料金の名称（例: 鑑定料、指名料、施術料）', max_length=50, verbose_name='料金ラベル'),
        ),
        migrations.AddField(
            model_name='store',
            name='photo_2',
            field=models.ImageField(blank=True, upload_to='store_photos/', verbose_name='店舗写真2'),
        ),
        migrations.AddField(
            model_name='store',
            name='photo_3',
            field=models.ImageField(blank=True, upload_to='store_photos/', verbose_name='店舗写真3'),
        ),
        migrations.CreateModel(
            name='TaxServiceCharge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='例: 消費税、深夜料金、サービス料', max_length=100, verbose_name='名称')),
                ('rate', models.DecimalField(decimal_places=2, help_text='パーセンテージで入力（例: 10.00）', max_digits=5, verbose_name='税率(%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('applies_after_hour', models.IntegerField(blank=True, help_text='この時間以降に適用（例: 22 = 22時以降）。空欄の場合は常時適用', null=True, verbose_name='適用開始時間')),
                ('sort_order', models.IntegerField(default=0, verbose_name='並び順')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_charges', to='booking.store', verbose_name='店舗')),
            ],
            options={
                'verbose_name': '税・サービス料',
                'verbose_name_plural': '税・サービス料設定',
                'ordering': ('store', 'sort_order'),
            },
        ),
    ]
