# Generated by Django 4.2.25 on 2026-03-16 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0071_notice_add_slug_published_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='google_maps_embed',
            field=models.TextField(blank=True, default='', help_text='Google Mapsの「共有→地図を埋め込む」からiframeコードを貼り付けてください', verbose_name='Google Maps埋め込みコード'),
        ),
    ]
