# Generated by Django 4.2.25 on 2026-03-16 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0072_store_google_maps_embed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftperiod',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='申請締切'),
        ),
    ]
