# Generated by Django 4.2.25 on 2026-03-17 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0073_shift_period_deadline_nullable'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreClosedDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='休業日')),
                ('reason', models.CharField(blank=True, max_length=100, verbose_name='理由')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closed_dates', to='booking.store')),
            ],
            options={
                'verbose_name': '休業日',
                'verbose_name_plural': '休業日',
                'unique_together': {('store', 'date')},
            },
        ),
    ]
