# Generated by Django 4.2.25 on 2026-03-17 03:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0074_storecloseddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftassignment',
            name='date',
            field=models.DateField(db_index=True, verbose_name='日付'),
        ),
        migrations.AlterField(
            model_name='shiftassignment',
            name='end_hour',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)], verbose_name='終了時間'),
        ),
        migrations.AlterField(
            model_name='shiftassignment',
            name='start_hour',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)], verbose_name='開始時間'),
        ),
        migrations.AlterField(
            model_name='shiftrequest',
            name='date',
            field=models.DateField(db_index=True, verbose_name='日付'),
        ),
        migrations.AlterField(
            model_name='shiftrequest',
            name='end_hour',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)], verbose_name='終了時間'),
        ),
        migrations.AlterField(
            model_name='shiftrequest',
            name='start_hour',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)], verbose_name='開始時間'),
        ),
        migrations.AddIndex(
            model_name='shiftassignment',
            index=models.Index(fields=['period', 'date'], name='idx_shiftasgn_period_date'),
        ),
        migrations.AddIndex(
            model_name='shiftassignment',
            index=models.Index(fields=['staff', 'date'], name='idx_shiftasgn_staff_date'),
        ),
        migrations.AddIndex(
            model_name='shiftassignment',
            index=models.Index(fields=['is_synced'], name='idx_shiftasgn_synced'),
        ),
        migrations.AddIndex(
            model_name='shiftrequest',
            index=models.Index(fields=['period', 'date'], name='idx_shiftreq_period_date'),
        ),
        migrations.AddIndex(
            model_name='shiftrequest',
            index=models.Index(fields=['staff', 'date'], name='idx_shiftreq_staff_date'),
        ),
    ]
