# Generated by Django 4.2.25 on 2026-03-17 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0075_shift_indexes_validators'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_address',
            field=models.TextField(blank=True, default='', verbose_name='配送先住所'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='メールアドレス'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='顧客名'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_phone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='電話番号'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipped_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='発送日時'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_note',
            field=models.TextField(blank=True, default='', verbose_name='発送メモ'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_status',
            field=models.CharField(choices=[('none', '発送不要'), ('pending', '発送待ち'), ('shipped', '発送済み'), ('delivered', '配達完了')], default='none', max_length=20, verbose_name='発送ステータス'),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='追跡番号'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='customer_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='予約者名'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.staff', verbose_name='キャスト'),
        ),
    ]
