# Generated by Django 4.2.25 on 2026-03-17 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0076_order_customer_address_order_customer_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftpublishhistory',
            name='action',
            field=models.CharField(choices=[('publish', '公開'), ('revoke', '撤回')], default='publish', max_length=10, verbose_name='操作'),
        ),
        migrations.AddField(
            model_name='shiftpublishhistory',
            name='reason',
            field=models.TextField(blank=True, default='', verbose_name='理由'),
        ),
        migrations.CreateModel(
            name='ShiftChangeLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('change_type', models.CharField(choices=[('revised', '修正'), ('deleted', '削除')], max_length=20, verbose_name='変更種別')),
                ('old_values', models.JSONField(default=dict, verbose_name='変更前')),
                ('new_values', models.JSONField(default=dict, verbose_name='変更後')),
                ('reason', models.TextField(blank=True, default='', verbose_name='変更理由')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='booking.shiftassignment')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='booking.staff')),
            ],
            options={
                'verbose_name': 'シフト変更ログ',
                'verbose_name_plural': 'シフト変更ログ',
                'ordering': ('-changed_at',),
            },
        ),
    ]
