# Generated by Django 4.2.25 on 2026-03-17 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0077_shiftpublishhistory_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='staff_type',
            field=models.CharField(choices=[('fortune_teller', 'キャスト'), ('store_staff', 'スタッフ')], db_index=True, default='fortune_teller', max_length=20, verbose_name='スタッフ種別'),
        ),
    ]
