# Generated by Django 4.2.25 on 2026-03-17 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0078_staff_type_label_rename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftpublishhistory',
            name='action',
            field=models.CharField(choices=[('publish', '公開'), ('revoke', '撤回'), ('reopen', '再募集')], default='publish', max_length=10, verbose_name='操作'),
        ),
    ]
