# Generated by Django 4.2.25 on 2026-03-18 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0079_add_reopen_action_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='show_admin_ec_shop',
            field=models.BooleanField(default=True, help_text='管理サイドバーに「オンラインショップ」を表示するかどうか', verbose_name='オンラインショップを表示'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='show_admin_inventory',
            field=models.BooleanField(default=True, help_text='管理サイドバーに「在庫管理」を表示するかどうか', verbose_name='在庫管理を表示'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='show_admin_menu_manage',
            field=models.BooleanField(default=True, help_text='管理サイドバーに「メニュー管理」を表示するかどうか', verbose_name='メニュー管理を表示'),
        ),
    ]
