# Generated by Django 4.2.25 on 2026-03-18 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0080_add_sidebar_visibility_toggles'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='show_admin_iot',
            field=models.BooleanField(default=True, help_text='管理サイドバーに「IoT管理」を表示するかどうか', verbose_name='IoT管理を表示'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='show_admin_order',
            field=models.BooleanField(default=True, help_text='管理サイドバーに「注文管理」を表示するかどうか', verbose_name='注文管理を表示'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='show_admin_order_history',
            field=models.BooleanField(default=True, help_text='管理サイドバーに「店内オーダー履歴」を表示するかどうか', verbose_name='店内オーダー履歴を表示'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='show_admin_pos',
            field=models.BooleanField(default=True, help_text='管理サイドバーに「レジ（POS）」を表示するかどうか', verbose_name='レジ（POS）を表示'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='show_admin_reservation',
            field=models.BooleanField(default=True, help_text='管理サイドバーに「予約管理」を表示するかどうか', verbose_name='予約管理を表示'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='show_admin_shift',
            field=models.BooleanField(default=True, help_text='管理サイドバーに「シフト」を表示するかどうか', verbose_name='シフト管理を表示'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='show_admin_staff_manage',
            field=models.BooleanField(default=True, help_text='管理サイドバーに「従業員管理」を表示するかどうか', verbose_name='従業員管理を表示'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='show_admin_table_order',
            field=models.BooleanField(default=True, help_text='管理サイドバーに「店舗管理」を表示するかどうか', verbose_name='店舗管理を表示'),
        ),
    ]
