# Generated by Django 4.2.25 on 2026-03-18 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0081_add_sidebar_feature_toggles'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminSidebarSettings',
            fields=[
            ],
            options={
                'verbose_name': '管理サイドバー設定',
                'verbose_name_plural': '管理サイドバー設定',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('booking.sitesettings',),
        ),
        migrations.AddField(
            model_name='staff',
            name='notify_booking',
            field=models.BooleanField(default=True, help_text='予約が入った時にLINEで通知を受け取る', verbose_name='予約通知'),
        ),
        migrations.AddField(
            model_name='staff',
            name='notify_business',
            field=models.BooleanField(default=True, help_text='管理者からの業務連絡をLINEで受け取る', verbose_name='業務連絡通知'),
        ),
        migrations.AddField(
            model_name='staff',
            name='notify_shift',
            field=models.BooleanField(default=True, help_text='シフト公開・変更時にLINEで通知を受け取る', verbose_name='シフト通知'),
        ),
    ]
