# Generated by Django 4.2.25 on 2026-03-18 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0082_staff_notification_prefs'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='can_see_inventory',
            field=models.BooleanField(default=False, help_text='ONにすると在庫管理メニューがサイドバーに表示されます', verbose_name='在庫管理を表示'),
        ),
        migrations.AddField(
            model_name='staff',
            name='can_see_orders',
            field=models.BooleanField(default=False, help_text='ONにすると注文管理メニューがサイドバーに表示されます', verbose_name='注文管理を表示'),
        ),
        migrations.AddField(
            model_name='staff',
            name='slot_duration',
            field=models.IntegerField(blank=True, choices=[(15, '15分'), (30, '30分'), (45, '45分'), (60, '60分')], default=None, help_text='未設定の場合は店舗設定を使用', null=True, verbose_name='1枠の時間(分)'),
        ),
    ]
