# Generated by Django 4.2.25 on 2026-03-18 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0084_rename_order_history_and_staff_evaluation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ECCategory',
            fields=[
            ],
            options={
                'verbose_name': 'EC商品カテゴリ',
                'verbose_name_plural': 'EC商品カテゴリ',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('booking.category',),
        ),
        migrations.CreateModel(
            name='ECProduct',
            fields=[
            ],
            options={
                'verbose_name': 'EC商品',
                'verbose_name_plural': 'EC商品',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('booking.product',),
        ),
    ]
