# Generated by Django 4.2.25 on 2026-03-18 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0085_ec_proxy_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftStaffRequirementOverride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日付')),
                ('staff_type', models.CharField(choices=[('fortune_teller', 'キャスト'), ('store_staff', 'スタッフ')], max_length=20, verbose_name='従業員種別')),
                ('required_count', models.PositiveIntegerField(default=1, verbose_name='必要人数')),
                ('reason', models.CharField(blank=True, default='', max_length=100, verbose_name='理由')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_requirement_overrides', to='booking.store')),
            ],
            options={
                'verbose_name': 'シフト必要人数（日付指定）',
                'verbose_name_plural': 'シフト必要人数（日付指定）',
                'ordering': ['date', 'staff_type'],
                'unique_together': {('store', 'date', 'staff_type')},
            },
        ),
        migrations.CreateModel(
            name='ShiftStaffRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, '月曜'), (1, '火曜'), (2, '水曜'), (3, '木曜'), (4, '金曜'), (5, '土曜'), (6, '日曜')], verbose_name='曜日')),
                ('staff_type', models.CharField(choices=[('fortune_teller', 'キャスト'), ('store_staff', 'スタッフ')], max_length=20, verbose_name='従業員種別')),
                ('required_count', models.PositiveIntegerField(default=1, verbose_name='必要人数')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_requirements', to='booking.store')),
            ],
            options={
                'verbose_name': 'シフト必要人数（曜日別）',
                'verbose_name_plural': 'シフト必要人数（曜日別）',
                'ordering': ['day_of_week', 'staff_type'],
                'unique_together': {('store', 'day_of_week', 'staff_type')},
            },
        ),
    ]
