# Generated by Django 4.2.25 on 2026-03-18 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0086_shift_staff_requirements'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_fee',
            field=models.PositiveIntegerField(default=0, verbose_name='送料'),
        ),
        migrations.CreateModel(
            name='ShippingConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False, verbose_name='送料を有効にする')),
                ('shipping_fee', models.PositiveIntegerField(default=0, verbose_name='送料（税込）')),
                ('free_shipping_threshold', models.PositiveIntegerField(default=0, help_text='0の場合は常に送料がかかります', verbose_name='送料無料の注文金額')),
                ('delivery_area', models.TextField(blank=True, default='', verbose_name='配達対応範囲')),
                ('note', models.TextField(blank=True, default='', verbose_name='送料に関する備考')),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_config', to='booking.store')),
            ],
            options={
                'verbose_name': '送料設定',
                'verbose_name_plural': '送料設定',
            },
        ),
    ]
