# Generated by Django 4.2.25 on 2026-03-19 02:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0087_order_shipping_fee_shippingconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='storescheduleconfig',
            name='min_shift_hours',
            field=models.IntegerField(default=2, help_text='自動調整時に割り当てる最低連続勤務時間', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='最低シフト時間(時間)'),
        ),
        migrations.CreateModel(
            name='ShiftSwapRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('swap', '交代'), ('cover', 'カバー'), ('absence', '欠勤')], max_length=10, verbose_name='申請種別')),
                ('reason', models.TextField(verbose_name='理由')),
                ('status', models.CharField(choices=[('pending', '申請中'), ('approved', '承認'), ('rejected', '却下'), ('cancelled', '取消')], default='pending', max_length=10, verbose_name='状態')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='承認日時')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_requests', to='booking.shiftassignment')),
                ('cover_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='swap_requests_received', to='booking.staff', verbose_name='交代先スタッフ')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap_requests_made', to='booking.staff', verbose_name='申請者')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='swap_requests_reviewed', to='booking.staff', verbose_name='承認者')),
            ],
            options={
                'verbose_name': 'シフト交代・欠勤申請',
                'verbose_name_plural': 'シフト交代・欠勤申請',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShiftVacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='日付')),
                ('start_hour', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)], verbose_name='開始時間')),
                ('end_hour', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)], verbose_name='終了時間')),
                ('staff_type', models.CharField(choices=[('fortune_teller', 'キャスト'), ('store_staff', 'スタッフ')], max_length=20, verbose_name='従業員種別')),
                ('required_count', models.PositiveIntegerField(verbose_name='必要人数')),
                ('assigned_count', models.PositiveIntegerField(default=0, verbose_name='配置済み人数')),
                ('status', models.CharField(choices=[('open', '募集中'), ('filled', '充足'), ('cancelled', '取消')], default='open', max_length=10, verbose_name='状態')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='booking.shiftperiod')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_vacancies', to='booking.store')),
            ],
            options={
                'verbose_name': 'シフト不足枠',
                'verbose_name_plural': 'シフト不足枠',
                'ordering': ['date', 'start_hour'],
                'unique_together': {('period', 'date', 'start_hour', 'staff_type')},
            },
        ),
    ]
