# Generated by Django 4.2.25 on 2026-03-19 08:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0088_shift_coverage_improvement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', '未払い'), ('partial', '一部支払'), ('paid', '支払済'), ('refunded', '返金済')], db_index=True, default='pending', max_length=20, verbose_name='支払状態'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_status',
            field=models.CharField(choices=[('none', '発送不要'), ('pending', '発送待ち'), ('shipped', '発送済み'), ('delivered', '配達完了')], db_index=True, default='none', max_length=20, verbose_name='発送ステータス'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='reservation_number',
            field=models.CharField(db_index=True, default=uuid.uuid4, editable=False, max_length=36, verbose_name='予約番号'),
        ),
    ]
