# Generated by Django 4.2.25 on 2026-03-19 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0089_order_index_and_uuid_cleanup'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='timezone',
            field=models.CharField(default='Asia/Tokyo', help_text='店舗のタイムゾーン (例: Asia/Tokyo)', max_length=50, verbose_name='タイムゾーン'),
        ),
    ]
