# Generated by Django 4.2.25 on 2026-03-19 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0090_store_timezone_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='checked_in_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkins_performed', to='booking.staff', verbose_name='チェックイン担当'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='checkin_backup_code',
            field=models.CharField(blank=True, help_text='口頭確認用6桁コード', max_length=6, null=True, verbose_name='バックアップコード'),
        ),
    ]
