# Generated by Django 4.2.25 on 2026-03-20 08:13

import booking.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0091_schedule_checkin_improvements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='api_key',
            field=booking.fields.EncryptedCharField(blank=True, default='', max_length=500, verbose_name='APIキー'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='api_secret',
            field=booking.fields.EncryptedCharField(blank=True, default='', max_length=500, verbose_name='APIシークレット'),
        ),
    ]
