# Generated by Django 4.2.25 on 2026-03-20 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0092_encrypted_payment_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='forced_language',
            field=models.CharField(blank=True, choices=[('', '自動（ブラウザ設定に従う）'), ('ja', '日本語'), ('zh-hant', '繁體中文'), ('en', 'English'), ('ko', '한국어'), ('es', 'Español'), ('pt', 'Português'), ('zh-hans', '简体中文')], default='', help_text='設定すると全ユーザーの表示言語をこの言語に固定します。空欄＝ブラウザ設定に従う', max_length=10, verbose_name='表示言語固定'),
        ),
    ]
