# Generated by Django 4.2.25 on 2026-03-22 09:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0093_forced_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='notification_emails',
            field=models.TextField(blank=True, default='', help_text='カンマ区切りで複数アドレス指定可', verbose_name='通知先メールアドレス'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='notification_enabled',
            field=models.BooleanField(default=False, verbose_name='メール通知を有効化'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='notification_rate_limit',
            field=models.IntegerField(default=10, help_text='1時間あたりの最大通知送信数', verbose_name='通知レート制限'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='shanon_api_url',
            field=models.URLField(blank=True, default='http://localhost:8765', verbose_name='SHANON API URL'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='shanon_notification_enabled',
            field=models.BooleanField(default=False, verbose_name='SHANON通知を有効化'),
        ),
        migrations.CreateModel(
            name='ErrorReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='エラー概要')),
                ('description', models.TextField(verbose_name='詳細説明')),
                ('severity', models.CharField(choices=[('critical', '緊急'), ('high', '高'), ('medium', '中'), ('low', '低')], default='medium', max_length=10, verbose_name='重要度')),
                ('status', models.CharField(choices=[('open', '未対応'), ('in_progress', '対応中'), ('resolved', '解決済み'), ('closed', 'クローズ')], default='open', max_length=20, verbose_name='ステータス')),
                ('steps_to_reproduce', models.TextField(blank=True, default='', verbose_name='再現手順')),
                ('screenshot', models.ImageField(blank=True, upload_to='error_reports/', verbose_name='スクリーンショット')),
                ('page_url', models.CharField(blank=True, default='', max_length=500, verbose_name='発生ページURL')),
                ('browser_info', models.CharField(blank=True, default='', max_length=300, verbose_name='ブラウザ情報')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='解決日時')),
                ('resolution_note', models.TextField(blank=True, default='', verbose_name='解決メモ')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_error_reports', to=settings.AUTH_USER_MODEL, verbose_name='担当者')),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_errors', to=settings.AUTH_USER_MODEL, verbose_name='報告者')),
            ],
            options={
                'verbose_name': 'エラー報告',
                'verbose_name_plural': 'エラー報告',
                'ordering': ['-created_at'],
            },
        ),
    ]
