# Generated by Django 4.2.25 on 2026-03-28 07:57

import booking.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0094_sitesettings_notification_emails_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('x', 'X (Twitter)')], max_length=10, verbose_name='プラットフォーム')),
                ('trigger_type', models.CharField(choices=[('shift_publish', 'シフト公開時'), ('daily_staff', '本日のスタッフ'), ('weekly_schedule', '週間スケジュール'), ('manual', '手動投稿')], max_length=20, verbose_name='トリガー種別')),
                ('content', models.TextField(verbose_name='投稿内容')),
                ('status', models.CharField(choices=[('pending', '投稿待ち'), ('posted', '投稿済み'), ('failed', '失敗'), ('skipped', 'スキップ（制限超過等）')], default='pending', max_length=10, verbose_name='ステータス')),
                ('external_post_id', models.CharField(blank=True, help_text='冪等性チェック用', max_length=100, verbose_name='外部投稿ID')),
                ('error_message', models.TextField(blank=True, verbose_name='エラーメッセージ')),
                ('retry_count', models.IntegerField(default=0, verbose_name='リトライ回数')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True, verbose_name='投稿日時')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_histories', to='booking.store', verbose_name='店舗')),
            ],
            options={
                'verbose_name': '投稿履歴',
                'verbose_name_plural': '投稿履歴',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('x', 'X (Twitter)')], default='x', max_length=10, verbose_name='プラットフォーム')),
                ('account_name', models.CharField(help_text='@username', max_length=100, verbose_name='アカウント名')),
                ('access_token', booking.fields.EncryptedCharField(blank=True, max_length=500, verbose_name='アクセストークン')),
                ('refresh_token', booking.fields.EncryptedCharField(blank=True, max_length=500, verbose_name='リフレッシュトークン')),
                ('token_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='トークン有効期限')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to='booking.store', verbose_name='店舗')),
            ],
            options={
                'verbose_name': 'SNSアカウント',
                'verbose_name_plural': 'SNSアカウント',
                'unique_together': {('store', 'platform')},
            },
        ),
        migrations.CreateModel(
            name='PostTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('x', 'X (Twitter)')], default='x', max_length=10, verbose_name='プラットフォーム')),
                ('trigger_type', models.CharField(choices=[('shift_publish', 'シフト公開時'), ('daily_staff', '本日のスタッフ'), ('weekly_schedule', '週間スケジュール'), ('manual', '手動投稿')], max_length=20, verbose_name='トリガー種別')),
                ('body_template', models.TextField(help_text='利用可能な変数: {store_name}, {date}, {staff_list}, {business_hours}, {month}', verbose_name='テンプレート本文')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_templates', to='booking.store', verbose_name='店舗')),
            ],
            options={
                'verbose_name': '投稿テンプレート',
                'verbose_name_plural': '投稿テンプレート',
                'unique_together': {('store', 'platform', 'trigger_type')},
            },
        ),
    ]
