# Generated by Django 4.2.25 on 2026-03-31 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0098_sns_drafts_knowledge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posthistory',
            name='platform',
            field=models.CharField(choices=[('x', 'X (Twitter)'), ('instagram', 'Instagram'), ('gbp', 'Google Business Profile')], max_length=10, verbose_name='プラットフォーム'),
        ),
        migrations.AlterField(
            model_name='posttemplate',
            name='platform',
            field=models.CharField(choices=[('x', 'X (Twitter)'), ('instagram', 'Instagram'), ('gbp', 'Google Business Profile')], default='x', max_length=10, verbose_name='プラットフォーム'),
        ),
        migrations.AlterField(
            model_name='socialaccount',
            name='platform',
            field=models.CharField(choices=[('x', 'X (Twitter)'), ('instagram', 'Instagram'), ('gbp', 'Google Business Profile')], default='x', max_length=10, verbose_name='プラットフォーム'),
        ),
        migrations.AlterField(
            model_name='store',
            name='embed_allowed_domains',
            field=models.TextField(blank=True, default='', help_text='iframe埋め込みを許可するドメイン（1行1ドメイン）。空の場合は全ドメイン許可', verbose_name='埋め込み許可ドメイン'),
        ),
        migrations.CreateModel(
            name='StoreTheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_color', models.CharField(default='#8c876c', help_text='ナビゲーション・ヘッダー背景色', max_length=7, verbose_name='プライマリカラー')),
                ('secondary_color', models.CharField(default='#f1f0ec', help_text='サイドバー・カード背景色', max_length=7, verbose_name='セカンダリカラー')),
                ('accent_color', models.CharField(default='#b8860b', help_text='ボタン・リンクのハイライト色', max_length=7, verbose_name='アクセントカラー')),
                ('text_color', models.CharField(default='#333333', help_text='本文テキスト色', max_length=7, verbose_name='テキストカラー')),
                ('header_bg_color', models.CharField(default='#8c876c', max_length=7, verbose_name='ヘッダー背景色')),
                ('footer_bg_color', models.CharField(default='#333333', max_length=7, verbose_name='フッター背景色')),
                ('heading_font', models.CharField(default='Hiragino Kaku Gothic Pro', max_length=100, verbose_name='見出しフォント')),
                ('body_font', models.CharField(default='Hiragino Kaku Gothic Pro', max_length=100, verbose_name='本文フォント')),
                ('logo', models.ImageField(blank=True, help_text='ヘッダーに表示するロゴ画像', upload_to='themes/logos/', verbose_name='ロゴ')),
                ('favicon', models.ImageField(blank=True, upload_to='themes/favicons/', verbose_name='ファビコン')),
                ('preset', models.CharField(choices=[('default', 'デフォルト'), ('elegant', 'エレガント'), ('modern', 'モダン'), ('natural', 'ナチュラル'), ('luxury', 'ラグジュアリー'), ('pop', 'ポップ'), ('japanese', '和風'), ('custom', 'カスタム')], default='default', max_length=50, verbose_name='テーマプリセット')),
                ('custom_css', models.TextField(blank=True, default='', help_text='追加CSSを記述できます（上級者向け）', verbose_name='カスタムCSS')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='store_theme', to='booking.store', verbose_name='店舗')),
            ],
            options={
                'verbose_name': '店舗テーマ',
                'verbose_name_plural': '店舗テーマ',
            },
        ),
    ]
