# Generated by Django 4.2.25 on 2026-03-31 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0099_store_theme'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionSchema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(max_length=50, unique=True, verbose_name='セクションタイプ')),
                ('label', models.CharField(max_length=100, verbose_name='表示名')),
                ('description', models.TextField(blank=True, default='', verbose_name='説明')),
                ('icon', models.CharField(blank=True, default='', help_text='FontAwesome アイコンクラス名', max_length=50, verbose_name='アイコン')),
                ('schema_json', models.JSONField(default=dict, help_text='設定UIを自動生成するためのJSON Schema', verbose_name='設定スキーマ')),
                ('default_settings', models.JSONField(default=dict, verbose_name='デフォルト設定')),
                ('template_name', models.CharField(help_text='例: booking/sections/hero_banner.html', max_length=200, verbose_name='テンプレート名')),
            ],
            options={
                'verbose_name': 'セクションスキーマ',
                'verbose_name_plural': 'セクションスキーマ',
            },
        ),
        migrations.CreateModel(
            name='PageLayout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_type', models.CharField(choices=[('home', 'トップページ'), ('staff_list', 'スタッフ一覧'), ('staff_detail', 'スタッフ詳細'), ('shop', 'ショップ'), ('notice_list', 'お知らせ一覧')], max_length=50, verbose_name='ページ種別')),
                ('sections_json', models.JSONField(default=list, help_text='セクションの並び順・表示/非表示・設定をJSON配列で保持', verbose_name='セクション構成')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_layouts', to='booking.store', verbose_name='店舗')),
            ],
            options={
                'verbose_name': 'ページレイアウト',
                'verbose_name_plural': 'ページレイアウト',
                'unique_together': {('store', 'page_type')},
            },
        ),
    ]
