# Generated by Django 4.2.25 on 2026-03-31 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0100_page_layout'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='テンプレート名')),
                ('description', models.TextField(blank=True, default='', verbose_name='説明')),
                ('thumbnail', models.ImageField(blank=True, upload_to='page_templates/', verbose_name='サムネイル')),
                ('category', models.CharField(choices=[('salon', 'サロン'), ('fortune', '占いサロン'), ('nail', 'ネイルサロン'), ('hair', 'ヘアサロン'), ('general', '汎用')], default='general', max_length=20, verbose_name='カテゴリ')),
                ('grapesjs_data', models.JSONField(default=dict, verbose_name='GrapesJSデータ')),
                ('html_content', models.TextField(blank=True, default='', verbose_name='HTML')),
                ('css_content', models.TextField(blank=True, default='', verbose_name='CSS')),
                ('is_system', models.BooleanField(default=True, help_text='システム提供テンプレートはユーザーが削除できません', verbose_name='システムテンプレート')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
            ],
            options={
                'verbose_name': 'ページテンプレート',
                'verbose_name_plural': 'ページテンプレート',
            },
        ),
        migrations.CreateModel(
            name='CustomPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='ページタイトル')),
                ('slug', models.SlugField(help_text='公開URLに使用されます（例: spring-campaign）', max_length=200, verbose_name='URLスラッグ')),
                ('page_type', models.CharField(choices=[('landing', 'ランディングページ'), ('campaign', 'キャンペーンページ'), ('custom', 'フリーページ')], default='custom', max_length=20, verbose_name='ページ種別')),
                ('grapesjs_data', models.JSONField(default=dict, help_text='エディタの状態（コンポーネントツリー・スタイル等）', verbose_name='GrapesJSデータ')),
                ('html_content', models.TextField(blank=True, default='', help_text='レンダリング済みHTML', verbose_name='HTML')),
                ('css_content', models.TextField(blank=True, default='', help_text='カスタムCSS', verbose_name='CSS')),
                ('is_published', models.BooleanField(default=False, verbose_name='公開')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='公開日時')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_pages', to='booking.store', verbose_name='店舗')),
            ],
            options={
                'verbose_name': 'カスタムページ',
                'verbose_name_plural': 'カスタムページ',
                'unique_together': {('store', 'slug')},
            },
        ),
    ]
