# Generated by Django 4.2.25 on 2026-04-02 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0104_savedblock'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='cancel_token',
            field=models.CharField(blank=True, help_text='顧客キャンセル用8桁コード', max_length=8, null=True, unique=True, verbose_name='キャンセル番号'),
        ),
    ]
