# Generated by Django 4.2.25 on 2026-04-02 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0106_backfill_cancel_tokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='refund_completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='返金完了日時'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='refund_completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds_processed', to='booking.staff', verbose_name='返金処理者'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='refund_note',
            field=models.TextField(blank=True, default='', verbose_name='返金備考'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='refund_status',
            field=models.CharField(choices=[('none', '返金不要'), ('pending', '返金待ち'), ('completed', '返金済み')], default='none', max_length=20, verbose_name='返金ステータス'),
        ),
    ]
