# Generated by Django 4.2.25 on 2026-04-02 06:27

from django.db import migrations


def backfill_refund_pending(apps, schema_editor):
    """キャンセル済み＋有料予約のrefund_statusをpendingに設定。"""
    Schedule = apps.get_model('booking', 'Schedule')
    Schedule.objects.filter(
        is_cancelled=True,
        price__gte=100,
        refund_status='none',
    ).update(refund_status='pending')


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0107_schedule_refund_fields'),
    ]

    operations = [
        migrations.RunPython(backfill_refund_pending, migrations.RunPython.noop),
    ]
