# Generated by Django 4.2.25 on 2026-04-02 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0108_backfill_refund_pending'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='maintenance_message',
            field=models.TextField(blank=True, default='', help_text='カスタムメッセージ（空の場合はデフォルト表示）', verbose_name='メンテナンスメッセージ'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='maintenance_mode',
            field=models.BooleanField(default=False, help_text='ONにするとログイン済みスタッフ以外にメンテナンス画面を表示', verbose_name='メンテナンスモード'),
        ),
    ]
