# Generated by Django 4.2.25 on 2026-04-02 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0109_sitesettings_maintenance'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='store',
            field=models.ForeignKey(blank=True, help_text='未設定の場合はスタッフの主店舗', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='booking.store', verbose_name='予約店舗'),
        ),
        migrations.AddField(
            model_name='shiftassignment',
            name='store',
            field=models.ForeignKey(blank=True, help_text='未設定の場合はスタッフの主店舗', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shift_assignments', to='booking.store', verbose_name='出勤店舗'),
        ),
        migrations.AddIndex(
            model_name='shiftassignment',
            index=models.Index(fields=['store', 'date'], name='idx_shiftasgn_store_date'),
        ),
    ]
