# Generated by Django 4.2.25 on 2026-04-02 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0111_backfill_schedule_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='threads_url',
            field=models.URLField(blank=True, default='', help_text='例: https://www.threads.com/@youraccount', verbose_name='Threads URL'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tiktok_url',
            field=models.URLField(blank=True, default='', help_text='例: https://www.tiktok.com/@youraccount', verbose_name='TikTok URL'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='twitter_url',
            field=models.URLField(blank=True, default='', help_text='例: https://x.com/youraccount', verbose_name='X(Twitter) URL'),
        ),
    ]
