# Generated by Django 4.2.25 on 2026-04-02 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0112_sitesettings_threads_tiktok'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ventilationautocontrol',
            options={'verbose_name': '自動制御', 'verbose_name_plural': '自動制御'},
        ),
    ]
