# Generated by Django 4.2.25 on 2026-04-02 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0113_rename_ventilation_verbose'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='sidebar_order',
            field=models.JSONField(blank=True, default=list, help_text='セクションの表示順序。例: ["notice","sns","media","external_links","company"]', verbose_name='サイドバー並び順'),
        ),
    ]
