# Generated by Django 4.2.25 on 2026-04-02 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0114_sitesettings_sidebar_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineCustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_user_hash', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='LINEユーザーIDハッシュ')),
                ('line_user_enc', models.TextField(verbose_name='LINEユーザーID(暗号化)')),
                ('display_name', models.CharField(blank=True, default='', max_length=255, verbose_name='表示名')),
                ('is_friend', models.BooleanField(default=True, verbose_name='友だち')),
                ('first_visit_at', models.DateTimeField(auto_now_add=True, verbose_name='初回訪問')),
                ('last_visit_at', models.DateTimeField(auto_now=True, verbose_name='最終訪問')),
                ('visit_count', models.IntegerField(default=0, verbose_name='来店回数')),
                ('total_spent', models.IntegerField(default=0, verbose_name='累計金額')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='タグ')),
                ('segment', models.CharField(choices=[('new', '新規'), ('regular', 'リピーター'), ('vip', 'VIP'), ('dormant', '休眠')], default='new', max_length=20, verbose_name='セグメント')),
                ('blocked_at', models.DateTimeField(blank=True, null=True, verbose_name='ブロック日時')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='line_customers', to='booking.store', verbose_name='店舗')),
            ],
            options={
                'verbose_name': 'LINE顧客',
                'verbose_name_plural': 'LINE顧客',
            },
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='line_chatbot_enabled',
            field=models.BooleanField(default=False, help_text='LINEからのチャットボット予約を有効化', verbose_name='LINEチャットボット'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='line_reminder_enabled',
            field=models.BooleanField(default=False, help_text='予約前日・当日のLINEリマインダー送信を有効化', verbose_name='LINEリマインダー'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='line_segment_enabled',
            field=models.BooleanField(default=False, help_text='顧客セグメント別のLINE配信機能を有効化', verbose_name='LINEセグメント配信'),
        ),
        migrations.AlterField(
            model_name='securitylog',
            name='event_type',
            field=models.CharField(choices=[('login_success', 'ログイン成功'), ('login_fail', 'ログイン失敗'), ('api_auth_fail', 'API認証失敗'), ('permission_denied', '権限拒否'), ('suspicious_request', '不審なリクエスト'), ('admin_action', '管理操作'), ('maintenance_on', 'メンテナンス開始'), ('maintenance_off', 'メンテナンス終了'), ('server_error', 'サーバーエラー')], db_index=True, max_length=30, verbose_name='イベント種別'),
        ),
        migrations.CreateModel(
            name='LineMessageLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('reminder', 'リマインダー'), ('segment', 'セグメント配信'), ('chatbot', 'チャットボット'), ('system', 'システム')], max_length=30, verbose_name='種別')),
                ('content_preview', models.CharField(max_length=200, verbose_name='内容プレビュー')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='送信日時')),
                ('status', models.CharField(choices=[('sent', '送信済み'), ('failed', '失敗')], default='sent', max_length=10, verbose_name='ステータス')),
                ('error_detail', models.TextField(blank=True, default='', verbose_name='エラー詳細')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_logs', to='booking.linecustomer', verbose_name='顧客')),
            ],
            options={
                'verbose_name': 'LINE送信ログ',
                'verbose_name_plural': 'LINE送信ログ',
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['message_type', '-sent_at'], name='booking_lin_message_c269e7_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='linecustomer',
            index=models.Index(fields=['segment'], name='booking_lin_segment_1889a8_idx'),
        ),
        migrations.AddIndex(
            model_name='linecustomer',
            index=models.Index(fields=['store', 'segment'], name='booking_lin_store_i_e5ae88_idx'),
        ),
    ]
