# Generated by Django 4.2.25 on 2026-04-02 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0115_line_customer_and_messagelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='reminder_sent_day_before',
            field=models.BooleanField(default=False, verbose_name='前日リマインダー送信済み'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='reminder_sent_same_day',
            field=models.BooleanField(default=False, verbose_name='当日リマインダー送信済み'),
        ),
    ]
