# Generated by Django 4.2.25 on 2026-04-02 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0116_schedule_reminder_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='confirmation_status',
            field=models.CharField(choices=[('none', '通常'), ('pending', '確認待ち'), ('confirmed', '確定'), ('rejected', '却下')], default='none', max_length=20, verbose_name='確認ステータス'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='確認日時'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmations', to='booking.staff', verbose_name='確認者'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='rejection_reason',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='却下理由'),
        ),
    ]
