# Generated by Django 4.2.25 on 2026-04-03 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0117_schedule_confirmation_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval', models.CharField(choices=[('off', '無効'), ('minute', '毎分'), ('hourly', '毎時'), ('daily', '毎日')], default='off', max_length=10, verbose_name='バックアップ間隔')),
                ('s3_enabled', models.BooleanField(default=True, verbose_name='S3アップロード')),
                ('s3_bucket', models.CharField(default='mee-newfuhi-backups', max_length=200, verbose_name='S3バケット名')),
                ('local_retention_count', models.IntegerField(default=30, help_text='ローカルに保持するバックアップファイルの最大数', verbose_name='ローカル保持数')),
                ('s3_retention_days', models.IntegerField(default=90, help_text='S3上のバックアップを保持する日数', verbose_name='S3保持日数')),
                ('exclude_demo_data', models.BooleanField(default=True, help_text='ONにするとis_demo=Trueのレコードをバックアップから除外', verbose_name='デモデータを除外')),
                ('line_notify_enabled', models.BooleanField(default=True, help_text='バックアップ完了/失敗時にLINE Notifyで通知', verbose_name='LINE通知')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
            ],
            options={
                'verbose_name': 'バックアップ設定',
                'verbose_name_plural': 'バックアップ設定',
            },
        ),
        migrations.AddField(
            model_name='businessinsight',
            name='is_demo',
            field=models.BooleanField(db_index=True, default=False, verbose_name='デモデータ'),
        ),
        migrations.AddField(
            model_name='customerfeedback',
            name='is_demo',
            field=models.BooleanField(db_index=True, default=False, verbose_name='デモデータ'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_demo',
            field=models.BooleanField(db_index=True, default=False, verbose_name='デモデータ'),
        ),
        migrations.AddField(
            model_name='postransaction',
            name='is_demo',
            field=models.BooleanField(db_index=True, default=False, verbose_name='デモデータ'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='is_demo',
            field=models.BooleanField(db_index=True, default=False, verbose_name='デモデータ'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='demo_mode_enabled',
            field=models.BooleanField(default=False, help_text='ONにするとデモデータもダッシュボードに表示します。OFFで実データのみ表示', verbose_name='デモモード'),
        ),
        migrations.AddField(
            model_name='staffrecommendationresult',
            name='is_demo',
            field=models.BooleanField(db_index=True, default=False, verbose_name='デモデータ'),
        ),
        migrations.AddField(
            model_name='visitorcount',
            name='is_demo',
            field=models.BooleanField(db_index=True, default=False, verbose_name='デモデータ'),
        ),
        migrations.AddField(
            model_name='workattendance',
            name='is_demo',
            field=models.BooleanField(db_index=True, default=False, verbose_name='デモデータ'),
        ),
        migrations.CreateModel(
            name='BackupHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backup_file', models.CharField(blank=True, default='', max_length=500, verbose_name='ファイル名')),
                ('file_size_bytes', models.BigIntegerField(default=0, verbose_name='ファイルサイズ(bytes)')),
                ('status', models.CharField(choices=[('running', '実行中'), ('success', '成功'), ('failed', '失敗')], default='running', max_length=10, verbose_name='ステータス')),
                ('trigger', models.CharField(choices=[('scheduled', 'スケジュール'), ('manual', '手動')], default='scheduled', max_length=10, verbose_name='トリガー')),
                ('s3_uploaded', models.BooleanField(default=False, verbose_name='S3アップロード済み')),
                ('s3_key', models.CharField(blank=True, default='', max_length=500, verbose_name='S3キー')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='エラーメッセージ')),
                ('duration_seconds', models.FloatField(default=0, verbose_name='所要時間(秒)')),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='開始日時')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完了日時')),
            ],
            options={
                'verbose_name': 'バックアップ履歴',
                'verbose_name_plural': 'バックアップ履歴',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['status', '-started_at'], name='booking_bac_status_0fb7ac_idx')],
            },
        ),
    ]
