# Generated by Django 4.2.25 on 2026-04-04 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0119_schedule_embed_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancestamp',
            name='is_demo',
            field=models.BooleanField(db_index=True, default=False, verbose_name='デモデータ'),
        ),
    ]
