# Generated by Django 4.2.25 on 2026-04-04 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0120_attendancestamp_is_demo'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftassignment',
            name='is_demo',
            field=models.BooleanField(db_index=True, default=False, verbose_name='デモデータ'),
        ),
        migrations.AddField(
            model_name='shiftperiod',
            name='is_demo',
            field=models.BooleanField(db_index=True, default=False, verbose_name='デモデータ'),
        ),
    ]
