# Generated by Django 4.2.25 on 2026-04-06 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0121_shift_is_demo'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='pen_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='ペンネーム'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='free_booking_mode',
            field=models.BooleanField(default=False, help_text='ONにすると全予約が決済スキップ・即確定になります', verbose_name='無料予約モード'),
        ),
    ]
