# Generated by Django 4.2.25 on 2026-04-08 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0122_free_booking_mode_and_pen_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storescheduleconfig',
            name='slot_duration',
            field=models.IntegerField(choices=[(30, '30分'), (60, '60分（デフォルト）')], default=60, help_text='カレンダーの1コマの長さ', verbose_name='予約枠の単位'),
        ),
    ]
