# Generated by Django 4.2.25 on 2026-04-08 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0123_alter_storescheduleconfig_slot_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='regular_holiday',
            field=models.CharField(blank=True, default='', help_text='定休日なしの場合は空欄', max_length=255, verbose_name='定休日'),
        ),
    ]
