# Generated by Django 4.2.25 on 2026-04-08 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0124_alter_store_regular_holiday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftassignment',
            name='color',
            field=models.CharField(default='#4F86C6', max_length=7, verbose_name='表示色'),
        ),
        migrations.AlterField(
            model_name='shifttemplate',
            name='color',
            field=models.CharField(default='#4F86C6', max_length=7, verbose_name='表示色'),
        ),
    ]
