# Generated by Django 4.2.25 on 2026-04-08 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0125_change_default_shift_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftassignment',
            name='color',
            field=models.CharField(default='#3B82F6', max_length=7, verbose_name='表示色'),
        ),
        migrations.AlterField(
            model_name='shifttemplate',
            name='color',
            field=models.CharField(default='#3B82F6', max_length=7, verbose_name='表示色'),
        ),
    ]
