# Generated by Django 4.2.25 on 2026-04-14 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0126_revert_default_shift_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posthistory',
            name='platform',
            field=models.CharField(choices=[('x', 'X (Twitter)'), ('instagram', 'Instagram'), ('gbp', 'Google Business Profile'), ('tiktok', 'TikTok')], max_length=10, verbose_name='プラットフォーム'),
        ),
        migrations.AlterField(
            model_name='posttemplate',
            name='platform',
            field=models.CharField(choices=[('x', 'X (Twitter)'), ('instagram', 'Instagram'), ('gbp', 'Google Business Profile'), ('tiktok', 'TikTok')], default='x', max_length=10, verbose_name='プラットフォーム'),
        ),
        migrations.AlterField(
            model_name='socialaccount',
            name='platform',
            field=models.CharField(choices=[('x', 'X (Twitter)'), ('instagram', 'Instagram'), ('gbp', 'Google Business Profile'), ('tiktok', 'TikTok')], default='x', max_length=10, verbose_name='プラットフォーム'),
        ),
    ]
