# Generated by Django 4.2.25 on 2026-04-14 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0127_alter_posthistory_platform_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='draftpost',
            index=models.Index(fields=['store', 'status'], name='draftpost_store_status'),
        ),
        migrations.AddIndex(
            model_name='draftpost',
            index=models.Index(fields=['-created_at'], name='draftpost_created'),
        ),
        migrations.AddIndex(
            model_name='draftpost',
            index=models.Index(fields=['target_date'], name='draftpost_target_date'),
        ),
        migrations.AddIndex(
            model_name='posthistory',
            index=models.Index(fields=['store', 'platform'], name='posthistory_store_platform'),
        ),
        migrations.AddIndex(
            model_name='posthistory',
            index=models.Index(fields=['status'], name='posthistory_status'),
        ),
        migrations.AddIndex(
            model_name='posthistory',
            index=models.Index(fields=['-created_at'], name='posthistory_created'),
        ),
    ]
