# Generated by Django 4.2.25 on 2026-04-15 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0128_add_social_posting_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='sns_daily_staff_enabled',
            field=models.BooleanField(default=True, help_text='毎日09:30にスタッフ情報を自動投稿', verbose_name='毎日スタッフ投稿'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='sns_drafts_generation_enabled',
            field=models.BooleanField(default=True, help_text='毎日08:00にAI下書きを自動生成', verbose_name='下書き自動生成'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='sns_scheduled_posts_enabled',
            field=models.BooleanField(default=True, help_text='予約投稿を5分ごとにチェック・実行', verbose_name='予約投稿実行'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='sns_weekly_schedule_enabled',
            field=models.BooleanField(default=True, help_text='毎週月曜10:00に週間スケジュールを自動投稿', verbose_name='週間スケジュール投稿'),
        ),
    ]
