# Generated by Django 4.2.25 on 2026-04-15 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0129_add_sns_posting_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='help_tour_auto_start',
            field=models.BooleanField(default=True, help_text='ONにすると各管理画面に初回アクセス時にヘルプガイドを自動表示します', verbose_name='ヘルプガイド自動表示'),
        ),
    ]
