"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 2.2.9.
"""

import os
import datetime
import logging

from dotenv import load_dotenv


# ====================================
# Paths
# ====================================
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# ====================================
# .env loading (switch by ENV)
# ====================================
# Usage:
#   export ENV=local
#   export ENV=production
#
# Priority:
#   1) .env.<ENV>
#   2) .env (optional fallback)
ENV = os.getenv("ENV", "local").strip().lower()

env_candidates = [
    os.path.join(BASE_DIR, f".env.{ENV}"),
    os.path.join(BASE_DIR, ".env"),
]

_loaded = False
for p in env_candidates:
    if os.path.exists(p):
        load_dotenv(p, override=False)
        _loaded = True
        break


# ====================================
# Helpers
# ====================================
def env_required(key: str) -> str:
    val = os.getenv(key)
    if val is None or str(val).strip() == "":
        raise RuntimeError(f"Missing required env var: {key}")
    return val


def env_bool(key: str, default: bool = False) -> bool:
    val = os.getenv(key)
    if val is None:
        return default
    return val.strip().lower() in ("1", "true", "yes", "y", "on")


def env_list(key: str, default=None):
    if default is None:
        default = []
    val = os.getenv(key)
    if not val:
        return default
    return [x.strip() for x in val.split(",") if x.strip()]


def env_int(key: str, default: int) -> int:
    """
    Parse int env var safely.

    Treat missing/empty as default, and raise a clear error for non-numeric values.
    """
    val = os.getenv(key)
    if val is None or str(val).strip() == "":
        return default
    try:
        return int(str(val).strip())
    except ValueError:
        raise RuntimeError(f"Invalid int env var: {key}={val!r}")


# ====================================
# Core
# ====================================
SECRET_KEY = env_required("SECRET_KEY")
DEBUG = env_bool("DEBUG", False)
ALLOWED_HOSTS = env_list("ALLOWED_HOSTS", ["127.0.0.1", "localhost", "testserver"])

# テスト環境での追加設定
import sys
if 'test' in sys.argv or 'shell' in sys.argv:
    if 'testserver' not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append('testserver')


# ====================================
# Applications
# ====================================
INSTALLED_APPS = [
    "social_django",
    "booking.apps.BookingConfig",

    # カスタム認証ラベル（authを内包している前提）
    "booking.custom_auth.CustomAuthConfig",

    # Django standard
    "django.contrib.admin",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # DRF
    "rest_framework",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    # "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "social_core.backends.line.LineOAuth2",
]

ROOT_URLCONF = "project.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            os.path.join(BASE_DIR, "templates"),
            os.path.join(BASE_DIR, "booking", "templates"),
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "django.template.context_processors.i18n",
                "booking.context_processors.global_context",
                "social_django.context_processors.backends",
                "social_django.context_processors.login_redirect",
            ],
        },
    },
]

WSGI_APPLICATION = "project.wsgi.application"


# ====================================
# Database
# ====================================
DB_ENGINE = os.getenv("DB_ENGINE", "django.db.backends.sqlite3")
DB_NAME = os.getenv("DB_NAME", os.path.join(BASE_DIR, "db.sqlite3"))

DATABASES = {
    "default": {
        "ENGINE": DB_ENGINE,
        "NAME": DB_NAME,
    }
}


# ====================================
# Password validation
# ====================================
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]


# ====================================
# Logging
# ====================================
LOG_LEVEL = os.getenv("LOG_LEVEL", "DEBUG" if DEBUG else "INFO")
LOG_FILE = os.getenv("LOG_FILE", os.path.join(BASE_DIR, "debug.log"))

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {"class": "logging.StreamHandler"},
        "file": {
            "level": LOG_LEVEL,
            "class": "logging.FileHandler",
            "filename": LOG_FILE,
        },
    },
    "root": {
        "handlers": ["console", "file"],
        "level": LOG_LEVEL,
    },
}

logger = logging.getLogger(__name__)
logger.info("settings loaded (ENV=%s, DEBUG=%s, env_loaded=%s)", ENV, DEBUG, _loaded)


# ====================================
# I18N / TZ
# ====================================
LANGUAGE_CODE = "ja"
TIME_ZONE = "Asia/Tokyo"
USE_I18N = True
USE_L10N = True
USE_TZ = True

LANGUAGES = [
    ("ja", "日本語"),
    ("en", "English"),
    ("zh-hant", "繁體中文"),
    ("zh-hans", "简体中文"),
    ("ko", "한국어"),
    ("es", "Español"),
    ("pt", "Português"),
]

LOCALE_PATHS = [os.path.join(BASE_DIR, "locale")]


# ====================================
# Static / Media
# ====================================
STATIC_URL = "/static/"
STATIC_ROOT = os.getenv("STATIC_ROOT", os.path.join(BASE_DIR, "staticfiles"))
STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")]

MEDIA_URL = "/media/"
MEDIA_ROOT = os.getenv("MEDIA_ROOT", os.path.join(BASE_DIR, "media"))


# ====================================
# Holidays (existing list 그대로)
# ====================================
PUBLIC_HOLIDAYS = [
    # 2020
    datetime.date(year=2020, month=1, day=1),
    datetime.date(year=2020, month=1, day=13),
    datetime.date(year=2020, month=2, day=11),
    datetime.date(year=2020, month=2, day=23),
    datetime.date(year=2020, month=2, day=24),
    datetime.date(year=2020, month=3, day=20),
    datetime.date(year=2020, month=4, day=29),
    datetime.date(year=2020, month=5, day=3),
    datetime.date(year=2020, month=5, day=4),
    datetime.date(year=2020, month=5, day=5),
    datetime.date(year=2020, month=7, day=20),
    datetime.date(year=2020, month=8, day=11),
    datetime.date(year=2020, month=9, day=21),
    datetime.date(year=2020, month=9, day=22),
    datetime.date(year=2020, month=10, day=12),
    datetime.date(year=2020, month=11, day=3),
    datetime.date(year=2020, month=11, day=23),

    # 2021
    datetime.date(year=2021, month=1, day=1),
    datetime.date(year=2021, month=1, day=11),
    datetime.date(year=2021, month=2, day=11),
    datetime.date(year=2021, month=2, day=23),
    datetime.date(year=2021, month=3, day=20),
    datetime.date(year=2021, month=4, day=29),
    datetime.date(year=2021, month=5, day=3),
    datetime.date(year=2021, month=5, day=4),
    datetime.date(year=2021, month=5, day=5),
    datetime.date(year=2021, month=7, day=19),
    datetime.date(year=2021, month=8, day=11),
    datetime.date(year=2021, month=9, day=20),
    datetime.date(year=2021, month=9, day=23),
    datetime.date(year=2021, month=10, day=11),
    datetime.date(year=2021, month=11, day=3),
    datetime.date(year=2021, month=11, day=23),
]


# ====================================
# Auth redirects
# ====================================
LOGIN_URL = "booking:login"
LOGIN_REDIRECT_URL = "booking:store_list"
LOGOUT_REDIRECT_URL = "booking:login"

DEFAULT_AUTO_FIELD = "django.db.models.AutoField"


# ====================================
# LINE / Payment / Webhook  (ALL required)
# ====================================
LINE_CHANNEL_ID = env_required("LINE_CHANNEL_ID")
LINE_CHANNEL_SECRET = env_required("LINE_CHANNEL_SECRET")
LINE_REDIRECT_URL = env_required("LINE_REDIRECT_URL")

LINE_ACCESS_TOKEN = env_required("LINE_ACCESS_TOKEN")

PAYMENT_API_KEY = env_required("PAYMENT_API_KEY")
PAYMENT_API_URL = env_required("PAYMENT_API_URL")

WEBHOOK_URL_BASE = env_required("WEBHOOK_URL_BASE")
CANCEL_URL = env_required("CANCEL_URL")


# ====================================
# Email (IoT gas alerts etc.)
# ====================================
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", "no-reply@example.com")

EMAIL_HOST = os.getenv("EMAIL_HOST", "")
EMAIL_PORT = env_int("EMAIL_PORT", 587)
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
EMAIL_USE_TLS = env_bool("EMAIL_USE_TLS", True)


# ====================================
# Celery
# ====================================
CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL", "redis://localhost:6379/0")

# 既存コード互換（あなたの settings で accept_content/task_serializer を使っている前提）
accept_content = env_list("CELERY_ACCEPT_CONTENT", ["json"])
task_serializer = os.getenv("CELERY_TASK_SERIALIZER", "json")


# ====================================
# LINE user id protection (required for your design)
# ====================================
LINE_USER_ID_ENCRYPTION_KEY = env_required("LINE_USER_ID_ENCRYPTION_KEY")
LINE_USER_ID_HASH_PEPPER = env_required("LINE_USER_ID_HASH_PEPPER")


# ====================================
# Security (production hardening)
# ====================================
if not DEBUG:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = "DENY"

    # Reverse proxy (Nginx/ALB) etc.
    # Example:
    # SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

    # Optional strong settings:
    # SECURE_SSL_REDIRECT = True
    # SECURE_HSTS_SECONDS = 31536000
    # SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    # SECURE_HSTS_PRELOAD = True